### PR TITLE
feat(tab): Add [showOverflow] input

### PR DESCRIPTION
**Pull request by zelliott**
### Motivation

Tabs hide their tab body overflow so that the tab body "slide-in" / "slide-out" animation effect works properly. This can lead to non-obvious visual bugs where drop shadows, ripples, and focus indicators are inadvertently clipped from view. The official guidance is to simply apply inner padding to the tab body, but this can mess with page flow and visual hierarchy if some content is insetted and other content isn't.

### Proposal

If the animation effect is disabled with `[animationDuration]="0"`, tabs no longer need to hide their overflow. Consequently, we should be able to reset the now unnecessary `overflow` styles to `overflow: visible` and instead toggle tab views with `display`.

This PR introduces a new input `[showOverflow]` that does exactly that. Note that if `[animationDuration]` is non-zero, `[showOverflow]` must be `false`.

To reiterate, we'd prefer to simply just *always* remove the `overflow` styles, but they are a hard dependency of the slide animation. AFAICT, there's no way to show overflow while also hiding overflow as tab content slides in-and-out.

If the input and implementation are reasonable, I'm happy to add a few unit tests that validate some styles are set correctly.

### CODE REVIEW

**Comment by zelliott** [comment]
> I'm not a huge fan of adding inputs that basically toggle a single style. Couldn't the consumer override our built-in styles? Their specificity should be fairly low.

You're right that overriding the current styles is pretty easy for developers to do. It's basically something like this:

```
  .mat-tab-body-wrapper,
  .mat-tab-body-content,
  .mat-tab-body,
  .mat-tab-body.mat-tab-body-active {
    overflow: visible;
  }

  .mat-tab-body:not(.mat-tab-body-active) {
    display: none;
  }
```

I suppose in general, when configuring non-trivial (and relatively dangerous) styles such as `overflow` and `display`, I feel better going through an officially supported component input. I'm a little worried about the component's implementation changing, and subsequently breaking any CSS overrides.

**Comment by jelbourn** [comment]
Could we just make it `overflow: visible` all the time when the animation is disabled? 
(pending seeing how breaking that would be in Google)

**Comment by zelliott** [comment]
> Could we just make it `overflow: visible` all the time when the animation is disabled?
> (pending seeing how breaking that would be in Google)

I considered that. I thought that overflow behavior changing would be a weird side-effect of whether or not animation was enabled. But it might be a small price to pay to avoid supporting an additional input. Is there even a scenario where a developer would have animation off, but want overflow to be hidden?

**Comment by jelbourn** [comment]
I'll defer here to @andrewseguin ; keep in mind that any API we add here will also have to work for the MDC version, and we don't want to get into a competition with their styles if we can help it

**Comment by andrewseguin** [comment]
I'd be curious to see what the presubmit results look like if we default to `overflow: visible` for 0ms animation. Let's try that first, just to see what may break. It'd be nice to avoid adding a niche `Input` that depends on another being 0.

**Comment by zelliott** [comment]
> I'd be curious to see what the presubmit results look like if we default to `overflow: visible` for 0ms animation. Let's try that first, just to see what may break. It'd be nice to avoid adding a niche `Input` that depends on another being 0.

Sounds good. I updated the PR with that approach and will run a TGP.

**Comment by zelliott** [comment]
Sorry for the delay, was out last week.

There are lots of screenshot breakages when defaulting to `overflow: visible` for 0ms animation. The biggest issue seems to be UIs that were already overflowing, and already looked broken as elements were hidden, but now look *even more broken* because these elements are visible. There are also a lot of breakages that I don't understand (e.g. slight text rendering differences or scattered 1px diffs that I determined were not flakes).

Given there's concern around adding this input, and defaulting to `overflow: visible` for 0ms animation has a suite of non-trivial screenshot issues, I'm leaning towards just abandoning this PR unless someone feels strongly otherwise. Instead, I'll likely just inset the content of tab groups on an ad hoc basis.

**Comment by jelbourn** [comment]
Yeah, that seems like the best course of action for now. Once we fully get switched over to MDC it might be something to explore on their side.

**Pull request closed without merging**
