### PR TITLE
docs: fix typo in theming guide

### PR DESCRIPTION
**Pull request by dolphingarlic**

### CODE REVIEW

**Comment by dolphingarlic** [comment]
@googlebot I signed it!

**Review by crisbeto — COMMENTED** [review]
The change looks good, but the commit message doesn't match our validation. It should be something like `docs: fix typo in theming guide`.

**Comment by dolphingarlic** [comment]
Thanks for the heads-up @crisbeto. I've just changed the commit message

**Review by crisbeto — APPROVED** [review]
LGTM

**Pull request merged**
