### PR TITLE
build: add lint rules banning `new`-ing of Object, String, Number and Boolean

### PR DESCRIPTION
**Pull request by josephperrott**

### CODE REVIEW

**Comment by josephperrott** [comment]
The same changes were just proposed for `angular/angular` and I wanted to create this to match.  

The reason for doing the change is that there is no value brought from using these constructors, they all are less performant and/or more code than using the primitives directly.

In terms of having to bring in another set of lint rules, banning `new Object` isn't in the rules we already had, so I added the rules that we have in `angular/angular`

**Comment by crisbeto** [comment]
I agree with @devversion that this seems redundant, considering that it hasn't come up before on this repo.

**Comment by jelbourn** [comment]
Is there a downside to having these? I don't see it ever coming up, but I don't see a cost to having them anyway

**Comment by devversion** [comment]
I don't mind much. I was mostly asking for the motivation of doing this. The downside is that we add more packages which aren't necessarily needed. Also FYI: lint rules like this, visit each identifier most likely and cause overall IDE slow-down (if implemented badly; just in general here).

**Comment by jelbourn** [comment]
That's fair. I personally turn off tslint in my IDE because it's waaaaay too aggressive while I'm in the middle of writing something. Like, I know the identifier is unused, I just wrote it 2 seconds ago.

**Pull request merged**
