### PR TITLE
fix(material/slider): make valueChange emit only on change and not on…

### PR DESCRIPTION
**Pull request by wagnermaciel**
… input

Fixes https://github.com/angular/components/issues/26496

### CODE REVIEW

**Comment by mmalerba** [comment]
Is there a bug associated with this?

**Review by mmalerba — APPROVED** [review]

**Comment by angelaki** [comment]
Since the new behavior is just _different_ and not wrong, maybe it would be nice to switch the behavior (keeping the old one as default)? If interessnted, I'd adopt the PR regardingly.

**Comment by wagnermaciel** [comment]
@angelaki Technically the new behavior is wrong. The valueChange event should only emit on value change which is different from on input

**Comment by angelaki** [comment]
@wagnermaciel Ah, I see! If I'm interessted in all the intermediate values I should listen to `onInput`? But where to find this event? It doesn't seam to be part of the documentation (https://material.angular.io/components/slider/api). Thank you for clarification.

**Comment by wagnermaciel** [comment]
@angelaki Hey, yep you're right. With the latest implementation of the slider, the native browser inputs are exposed, which means you can just listen to `input` events directly on it as if it was an `<input type="range" />`.

I believe the syntax should be something like this:

```html
<mat-slider>
    <input matSliderThumb (input)="handleInput($event)">
</mat-slider>
```

**Pull request merged**
