### PR TITLE
refactor(material/theming): normalize config in all typography mixins for mdc components

### PR DESCRIPTION
**Pull request by mmalerba**
This is split off of #21778 which covers non-MDC conmponents as well

### CODE REVIEW

**Review by crisbeto — APPROVED** [review]
LGTM, but the CI is failing.

**Review by andrewseguin — APPROVED** [review]
LGTM - should this change be made in internal Google Material components as well?

**Comment by mmalerba** [comment]
Yeah, I need to look into the screenshot diffs for this PR because I wasn't really expecting any. But once it's in we should do the same for Google Material components

**Comment by annieyw** [comment]
@mmalerba  needs rebase

**Pull request merged**
