### PR TITLE
docs(material/snack-bar): Fix typo in snackbar jsdoc.

### PR DESCRIPTION
**Pull request by 12wrigja**

### CODE REVIEW

**Comment by 12wrigja** [comment]
This typo looks like it's also present in various other repos in the Angular org - do I need to submit a PR for each of those or is there some automation that looks at this file as a source of truth?

https://github.com/search?q=org%3Aangular+applie&type=code

**Comment by crisbeto** [comment]
All of these comments need to be fixed, but they can be done in this PR. Note that you'll have to change the commit message to start with `docs(material/snack-bar)` in order for the lint check to pass.

**Comment by 12wrigja** [comment]
> All of these comments need to be fixed, but they can be done in this PR.

Can you clarify? All the typos in that search (besides the one in snackbar.ts) are outside this git repo, so unless GH has some magic I'm unaware of they would all have to be separate PRs. Unless you meant that the fix within snackbar.ts is enough (and the others will get fixed as a result of this PR being merged)?

**Comment by mmalerba** [comment]
The other ones are generated from the line you changed, they'll be fixed automatically

**Pull request merged**
