### PR TITLE
feat(cdk-experimental/selection): Merge cdk–selection to the master

### PR DESCRIPTION
**Pull request by yifange**
Merge the cdk-selection branch to the master branch #18581

### CODE REVIEW

**Comment by jelbourn** [comment]
Caretaker note: we should fixup the commit messages while also preserving the individual comments

**Comment by andrewseguin** [comment]
Please rebase and then stick the "merge ready" label back on

**Comment by yifange** [comment]
I resolved the conflicts in Github's UI and it seems it created a merge commit. It looks all good but let me know if you want me to do it in another way.

I added back "merge ready", not sure about "commit message fixup" though.

**Comment by andrewseguin** [comment]
Unfortunately our script isn't able to preserve commits while also needing to fix some up.

I re-attempted your rebase and we should be good. Once the CI reports green then we can get this in

**Pull request merged**
