### PR TITLE
build: run partial compilation tests with linker JIT

### PR DESCRIPTION
**Pull request by devversion**
Runs partial compilation tests with the linker at JIT. This helps
validating the Angular linker to catch bugs as reported by Stackblitz
which relies on JIT compilation with its v1 non-webcontainer approach.

### CODE REVIEW

**Comment by devversion** [comment]
Currently blocked until the fix from Joost for `forwardRef` linker JIT compilation lands in framework.

**Review by josephperrott — APPROVED** [review]
LGTM

**Comment by zarend** [comment]
Hi @devversion 👋 , are we still trying to get this in :). LMK if we are, and I can try to merge it before merging other PR's that touch the same files to avoid a conflict.

**Comment by devversion** [comment]
@zarend Yeah, thx for the heads-up. I will rebase it and let you know! I think this shouldn't conflict anytime soon again

**Pull request merged**
