### PR TITLE
perf(material/tooltip): use unsubscribe rather than takeUntil to improve performance

### PR DESCRIPTION
**Pull request by johannesalt**
Use unsubscribe rather than takeUntil to improve performance

Managing subscriptions by using RxJS takeUntil() might have a negative impact on the over all performance. The takeUntil() operator take up to 0.1ms to unsubscribe from observable. In a small application with only about ten tooltips at once it should not be an issue, but with 1000 of tooltips it is. Basically RxJS takeUntil() is not very efficient in scaling. Use Subscription to manually managing the subscriptions.

### CODE REVIEW

**Comment by crisbeto** [comment]
Is there any evidence that this is actually a performance issue? Most of these subscriptions only happen while a tooltip is open and you usually can't have more than one tooltip open at a time (unless you somehow have multiple mouse cursors). Furthermore, the [`takeUntil` operator](https://github.com/ReactiveX/rxjs/blob/master/src/internal/operators/takeUntil.ts#L47) is basically just a `observable.subscribe(() => observer.unsubscribe())` under the hood which is identical to saving the subscription and unsubscribing.

**Comment by johannesalt** [comment]
I'd like to see an operation system which supports multiple cursors at the same time - could be a little bit buggy.

To answer your question: in one of my projects I need to use the tooltip directive in an angular material data table. The columns and rows can be resized and in case of that the content of the cell is truncated the user should be able to see the whole content on mouse over (tooltip). In addition to that, the users should be able to re-order the columns in the table. Unfortunately the re-ordering took currently up to 1s.

I used the profiler tool of the new angular dev tools chrome extension and one finding was that `ngDestroy` of the tooltip directive took up to 0.1ms. We're showing a lot of data at once - up to 100 columns and 50 rows.

I read in a blog post that `takeUntil()` is in comparison with manually managing of the subscription slower, so I'd hoped, that I can solve my performance issue by using subscriptions rather than `takeUntil()`.

**Comment by andrewseguin** [comment]
It's like your issue is related to rendering a large table instead of this. Can you provide a stackblitz showing the performance issue, and perhaps we can run that example with the tooltip fix to observe a difference?

**Comment by johannesalt** [comment]
@andrewseguin: I created a sample application. Please have a look: https://stackblitz.com/edit/angular-ivy-jbpocp?file=src/app/app.component.html

The performance issue occurred on click on the `Shuffle` button. It takes sometimes about a second to re-render all 25 rows.

Thanks for the code review.

**Pull request closed without merging**
