### PR TITLE
fix(checkbox): make checkbox display inline-block

### PR DESCRIPTION
**Pull request by tinayuangao**

### CODE REVIEW

**Comment by jelbourn** [comment]
What's the context here?

**Comment by tinayuangao** [comment]
By default the checkbox doesn't respect vertical margin and vertical padding

**Comment by jelbourn** [comment]
Caretaker note: will probably cause screenshot diffs

**Comment by josephperrott** [comment]
Targeting as patch as it looks like the number of effected screenshot diffs is surprisingly low.

**Pull request closed without merging**
