### PR TITLE
feat(google-maps): switch to non-deprecated API for clustering and su…

### PR DESCRIPTION
**Pull request by OgiSss**
This commit update map marker cluster and support map marker and map advanced marker. 

It's related to: 
#23695
#24853

### CODE REVIEW

**Review by crisbeto — CHANGES_REQUESTED** [review]
We have a change for this in already in https://github.com/angular/components/pull/24853. The challenge isn't really the code, but how to roll it out. We'll proceed with https://github.com/angular/components/pull/24853 once we've decided on it.

**Comment by OgiSss** [comment]
@crisbeto Based on your code i have created a PR to support clusters for both markers and advanced markers. I know that the API between old and new clusters are different but in my opinion it's good idea to update library especially that many people waiting for it. And my code support old markers and new markers. Let me know what do you think about it

**Comment by crisbeto** [comment]
I don't think that we would want to support both clustering APIs in a single component since it's too much responsibility for one component and it'll make it harder to delete later. I'll see if I can get https://github.com/angular/components/pull/24853 moving again.

**Comment by OgiSss** [comment]
I mean I have implemented only one clusterer (the new one) but with support for marker and advanced marker.

**Comment by LeLunZ** [comment]
@crisbeto support for the "new" markerclusterer is highly appreciated. 
I think the old one is deprecated now for over 2 years. 
With the markers beeing deprecated it now makes even less sense to use markerclustererplus.

The new one supports handling for both new and old markers, so I think this PR makes total sense.

I stopped using the angular components years ago, because they didn't support the newest changes with the algorithms and the render function. Thought after upgrading to 17 I can finally use them. But doesn't seem so...

**Comment by Siddhu-K** [comment]
Any chance this arrives in v18? I recently started using Angular Google Maps and started with the advanced markers due to the deprecation warning. I would like to use the marker clusters. 
Should I wait or use the normal markers?

**Comment by OgiSss** [comment]
@crisbeto  any decisions? I still can finish this task :)

**Comment by crisbeto** [comment]
Closing in favor of #29885.

**Pull request closed without merging**
