### PR TITLE
support an optional trackBy function in FlatTreeControl

### PR DESCRIPTION
**Pull request by leea10**
This is similar to trackBy in *ngFor and is critical for those of us who
use the redux pattern (i.e. NGRX) since we frequently replace our node references with
modified copies from the Store (as opposed to changing the state within the node objects
themselves)

### CODE REVIEW

**Comment by andrewseguin** [comment]
Two comments:
- The expansionModel cannot be `unknown`
- Currently this would be a breaking change and you'd have to wait until the next major to get it out

To resolve this, we can add a new type `K` that will represent the type returned by the `trackBy` function. We can default it to `T` so that it remains backwards compatible.

You can take the code from this commit and apply it to this PR and verify that it fits your use case: https://github.com/andrewseguin/components/commit/d0c1089118a83b48b9291eaf662b5a8a78058d77

**Comment by leea10** [comment]
Hi! Thank you for the suggested changes - I've applied them, but I'm not sure what these failing CircleCI tests are

**Comment by jelbourn** [comment]
[There'as a build failure](https://circleci.com/gh/angular/components/127258?utm_campaign=vcs-integration-link&utm_medium=referral&utm_source=github-build-link)
```
ERROR: /home/circleci/ng/src/cdk/tree/BUILD.bazel:28:1: Compiling TypeScript (devmode) //src/cdk/tree:unit_test_sources failed (Exit 1)
src/cdk/tree/control/flat-tree-control.spec.ts:147:5 - error TS2322: Type '(node: TestData) => string' is not assignable to type '(dataNode: TestData) => TestData'.
  Type 'string' is not assignable to type 'TestData'.

147     treeControl.trackBy = (node: TestData) => `${node.a} ${node.b} ${node.c}`;
```

**Comment by leea10** [comment]
Hello! Fixed up the failing tests, I'm not sure what that last check is though.

**Pull request merged**
