### PR TITLE
fix(material-experimental/mdc-radio): de-duplicate test harness logic

### PR DESCRIPTION
**Pull request by crisbeto**
Changes the MDC-based radio harnesses to extend the base ones directly since the logic is identical, aside from some selectors.

### CODE REVIEW

**Review by jelbourn — APPROVED** [review]
LGTM

**Comment by mmalerba** [comment]
I'm seeing the following error from this (and some of the other PRs to share harness code):
```
Type 'import("material/radio/testing/radio-harness").MatRadioButtonHarness[]' is not assignable to type 'import("material-experimental/mdc-radio/testing/radio-harness").MatRadioButtonHarness[]'.
  Type 'import("material/radio/testing/radio-harness").MatRadioButtonHarness' is not assignable to type 'import("material-experimental/mdc-radio/testing/radio-harness").MatRadioButtonHarness'.
    Property '_textLabel' is protected but type 'MatRadioButtonHarness' is not a class derived from 'MatRadioButtonHarness'.
```

**Comment by crisbeto** [comment]
It's odd that our own build didn't complain about it. Maybe we can flip on a compiler flag to make it behave closer to g3? Also is it possible that they're importing both the non-MDC and MDC harnesses and they're using one to type the variable and the other one to look up the elements?

**Comment by mmalerba** [comment]
That's what I assumed was happening at first, but no - they're not importing anything from radio/testing and the variables are explicitly typed with the class imported from mdc-radio/testing like I showed above.

**Comment by mmalerba** [comment]
Maybe it has something to do with the `with` function? this looks a little suspect:

```ts
return new HarnessPredicate<NonMdcMatRadioButtonHarness>(MatRadioButtonHarness, options)
```

**Comment by crisbeto** [comment]
I see, I managed to reproduce it locally too. It's only the second call that is causing the compilation error. I think that it'll have to use the same approach where we have a base class for the harnesses. I'll rework it and let you know when it's done.

**Comment by crisbeto** [comment]
Reworked the PR to avoid the compilation error.

**Comment by andrewseguin** [comment]
Passes TGP - will be merged on the next round

**Pull request merged**
