### PR TITLE
fix(schematics/card): Migrated to appearance=outlined wich is not the MDC standard

### PR DESCRIPTION
**Pull request by yatho**
The schematics change standard raised to outlined. I have deleted the rules in schematics.

Fixes https://github.com/angular/components/issues/27004

### CODE REVIEW

**Comment by wagnermaciel** [comment]
@mmalerba Correct me if I'm wrong here but isn't `appearance="outlined"` added to keep the card looking as similar to the legacy card as possible?

**Comment by yatho** [comment]
I have understood that was a mistake so I push this PR.

I am not sure that's what the correct solution of the issue https://github.com/angular/components/issues/27004.

**Comment by mmalerba** [comment]
I'm not actually sure why the schematics add the `appearance=outline`, maybe a mistake because the legacy card is elevated.

**Review by mmalerba — APPROVED** [review]
LGTM

**Pull request closed without merging**
