### PR TITLE
fix(multiple): cleanup references to legacy components in non-legacy components

### PR DESCRIPTION
**Pull request by mmalerba**

### CODE REVIEW

**Review by crisbeto — CHANGES_REQUESTED** [review]
I already have PRs out for button, progress bar and progress spinner that remove these references.

**Comment by mmalerba** [comment]
@crisbeto ok that's fine. I think mine covers a few other things (shared spec files, and some docs changes). you can either submit yours and I'll rebase, or we can just submit this one

**Comment by crisbeto** [comment]
Mine cover pretty much all the legacy cases too (e.g. shared spec files). I won't get to them until next week, but it should be fine to drop those three commits from this PR since they're independent of everything else.

**Comment by mmalerba** [comment]
aright I dropped them

**Review by crisbeto — APPROVED** [review]
LGTM. I had some time so I got mine passing TGP so they don't become a blocker.

**Pull request merged**
