### PR TITLE
fix(material/slider): ensure input is defined on Destroy

### PR DESCRIPTION
**Pull request by aitboudad**

### CODE REVIEW

**Comment by wagnermaciel** [comment]
@aitboudad What was the use case where the input was undefined on destroy?

**Comment by aitboudad** [comment]
@wagnermaciel It happens in some case where component are created dynamically, so you can manually destroy a component before  `ngAfterViewInit`. I think there is no guarantee that `ngAfterViewInit` will be called before `ngOnDestroy` in component lifecycle.

**Comment by wagnermaciel** [comment]
I'm having trouble understanding what you mean by dynamically. Could you provide a stackblitz example demonstrating the issue?

**Comment by aitboudad** [comment]
> what you mean by dynamically

I means render component using `ViewContainerRef::createComponent`.

> Could you provide a stackblitz example demonstrating the issue?

Please check the following example (check " Render Slider and Destroy"):

https://stackblitz.com/edit/angular-8wd8mi?file=src/app/app.component.html

Screenshot from 2023-04-14 21-41-18

**Comment by wagnermaciel** [comment]
I believe the better solution here would not be to try and make bypassing Angular lifecycle looks work, but instead to allow lifecycle hooks to occur normally. This can be accomplished using [NgZone](https://angular.io/api/core/NgZone)

https://stackblitz.com/edit/angular-8wd8mi-dnfxr2?file=src%2Fapp%2Fapp.component.ts

I strongly suggest the above solution because I don't think we can ensure all of our components can function properly if lifecycle hooks are getting skipped

**Comment by aitboudad** [comment]
I understand so its up to you :), bypassing Angular lifecycle can be useful for some cases (Ex: Detecting memory leak). Also there is not guarantee that the order of lifecycle will occur normally (Example of Angular router https://stackoverflow.com/a/58394473).

**Comment by wagnermaciel** [comment]
Sorry, I haven't had time to get back to this in a while. My hunch is that this isn't something we'll want to support, I'll discuss this with the rest of the team and give you an update on what the final verdict is 👍🏽

**Pull request closed without merging**
