### PR TITLE
fix(cdk/tree): add missing generic types to trackBy Fixes (#21364)

### PR DESCRIPTION
**Pull request by POFerro**
This PR is my sugestion to correct: #21364

### CODE REVIEW

**Review by crisbeto — COMMENTED** [review]
Thank you for the fix. Overall it looks good, but in order to make it green, you have to do the following:

1. Run `yarn accept-api tree` and `yarn accept-api cdk/tree` and commit the changed files.
2. There's some linting that requires commit titles to be formatted a certain way. In your case it should be prefixed by `fix(cdk/tree)`. While we're at it, it can also be renamed to something like `fix(cdk/tree): add missing generic types to trackBy` so it's a bit more descriptive.
3. Can you add a `Fixed #21364` to your message so the issue is closed automatically when we merge in the fix?

**Comment by POFerro** [comment]
Fixed #21364

**Comment by POFerro** [comment]
Hi @crisbeto ,

Thanks for the reply, please check if it's ok now.
Glad to contribute :).
Thanks

**Comment by crisbeto** [comment]
The title on your last commit looks ok, but the two before it are still wrong. You can try to squash the 3 commits together. Also sorry, but I made a typo in my last message. In should be `Fixes #21364`, not `Fixed #21364` and it should be part of the commit message.

**Comment by POFerro** [comment]
Hi @crisbeto ,

Sorry, don't know how to sqash the commits and update titles :(, tried a bunch of stuff, can you help me?
Also did another PR with the titles corrected if you prefer.

Thanks

**Pull request closed without merging**
