### PR TITLE
refactor(table): rename MatTableDataSource to ClientArrayTableDataSource

### LINKED ISSUE #14378: Rename MatTableDataSource to ClientArrayTableDataSource
I see too frequently people misunderstand the intent behind `MatTableDataSource`, thinking that it's meant to be the primary (or only) way to add data to the table. Renaming this, and more eminently presenting it in the docs as just one option would hopefully help clear this up.

### PR DESCRIPTION
**Pull request by crisbeto**
Renames the `MatTableDataSource` to `ClientArrayTableDataSource` to make it a bit clearer what it's supposed to be used for.

Fixes #14378.

### CODE REVIEW

**Review by jelbourn — DISMISSED** [review]
LGTM

@andrewseguin should also approve this before it goes in (since he might disagree)

**Comment by jelbourn** [comment]
Added to 11.0.0 milestone

**Comment by andrewseguin** [comment]
Needs rebase

**Comment by crisbeto** [comment]
I'm closing this since it's pretty breaking and way out of date. We can recreate it if we still think it's a good idea.

**Pull request closed without merging**
