### PR TITLE
feat(menu): Disable closing the menu when contents are clicked

### PR DESCRIPTION
**Pull request by fareesh**
Disables automatically closing the menu when the panel contents are clicked.

### CODE REVIEW

**Comment by fareesh** [comment]
I signed it!

**Comment by willshowell** [comment]
See https://github.com/angular/material2/pull/4842

**Comment by TheAifam5** [comment]
I think this can be closed if is already merged by someone else :)

**Comment by jelbourn** [comment]
Closing since we don't believe the menu should support this feature (https://github.com/angular/components/pull/4842#issuecomment-305031863)

**Pull request closed without merging**
