### PR TITLE
fix(material/card): use more specific selector for divider override

### LINKED ISSUE #23524: bug(Dividers and Cards): Mat-Divider at any level in a Mat-Card is set to position absolute
#### Reproduction
Stackblitz: https://stackblitz.com/edit/angular-shq1go?file=src%2Fapp%2Fdivider-overview-example.html

Steps to reproduce:
1.  Using a mat-divider within a mat-card. (the third example in the stackblitz is what i am pointing to. 
 
 
#### Expected Behavior

What behavior were you expecting to see?
should leave the divider where it was positioned within a child component. 
The layout should not change depending on if it exists in a mat-car or not.

#### Actual Behavior

What behavior did you actually see?
the divider gets absolute positioned to which pulls it out of where it should be located.
Also inset removes absolute but then also removes any margin that had been applied to the divider

#### Possible cause:
The cause seems to be from: https://github.com/angular/components/pull/5862
that created the class selector: `.mat-card .mat-divider-horizontal` 
There is no scope at what level the divider is used within a card .... so it can greatly impact the layout of some layouts. 

It does seem that mat-list does fix some of the issue, but if you have your own custom layout ... it will break it no matter the depth.

#### Proposed fix:
Could update the selector to be `.mat-card > .mat-divider-horizontal` and only apply to direct children. Or `.mat-card >.mat-list >.mat-divider-horizontal`

### PR DESCRIPTION
**Pull request by crisbeto**
Fixes that the card targets all dividers which may include ones placed inside child components.

Fixes #23524.

### CODE REVIEW

**Comment by crisbeto** [comment]
Caretaker note: this has a chance of screenshot failures if people didn't compose their card correctly.

**Comment by tmburnell** [comment]
I am the one that created the original issue, I want to point out one concern i had. 
The fix above might break this case
image
because the divider is not a direct child of the mat-card, it is actually a child of the mat-list.  
So i dont know if there needs to be an or so we dont break some people existing layouts.

**Comment by crisbeto** [comment]
I think that in that case the list should be the one responsible for the divider position.

**Review by jelbourn — APPROVED** [review]
LGTM

**Comment by Sergiobop** [comment]
Please merge this! Nice fix 👍

**Pull request merged**
