### PR TITLE
fix(multiple): include APP_ID in element IDs

### PR DESCRIPTION
**Pull request by jelbourn**
Many components generate element IDs, which are used primarily for accessible labeling. The IDs all use an incrementing number concatenated with some stirng specific to that component. This change add Angular's `APP_ID` into these IDs in order to avoid ID collisions in cases where there are multiple instances of Angular running on the same page.

### CODE REVIEW

**Review by crisbeto — COMMENTED** [review]
Should we have a common helper for this so in the future we only have one place we'd need to change?

**Comment by jelbourn** [comment]
Yeah, I could see having something like

```ts
let nextId = 0;

@Injectable()
class IdGenerator {
  appId = inject(APP_ID);
  generateId(prefix: string) {
    return `${prefix}${this.appId}${nextId++}`;
  }
}
```

I guess in `cdk/a11y` ? Not sure there's a more appropriate place for it

**Comment by crisbeto** [comment]
Yeah I think `cdk/a11y` would be appropriate for it.

**Review by mmalerba — APPROVED** [review]

**Comment by jelbourn** [comment]
Updated the PR to include an `IdGenerator` class (in its own commit) and then use that class in _most_ of the ID generation. I intentionally left stepper and tab-group because they do something slightly different

**Review by crisbeto — APPROVED** [review]

**Comment by crisbeto** [comment]
Closing in favor of https://github.com/angular/components/pull/29948.

**Pull request closed without merging**
