### PR TITLE
refactor(drag-drop): remove deprecated APIs for 9.0.0

### PR DESCRIPTION
**Pull request by crisbeto**
Cleans on the APIs that were marked as deprecated for 8.0 and 9.0. Also deprecates a few for 10.0 which were supposed to be removed in 9.0, but hadn't been marked correctly.

BREAKING CHANGES:
* `DropListRef.id` has been removed.
* `CdkDragConfig` has been replaced with `DragRefConfig`.
* `DragDropRegistry.getDropContainer` has been removed.
* `CdkDropListContainer` interface has been removed.
* `CDK_DROP_LIST_CONTAINER` has been replaced with `CDK_DROP_LIST`.
* `CdkDrag.boundaryElementSelector` has been replaced with `CdkDrag.boundaryElement`.
* `_ngZone` and `_viewportRuler` parameters in the `DropListRef` constructor are now required.
* `distance` parameter in `DropListRef.drop` is now required.

### CODE REVIEW

**Comment by jelbourn** [comment]
Should we have a migration for the renames?

**Comment by crisbeto** [comment]
I'm not sure how many people are actually going to hit them. The only document public API that was renamed is `boundaryElementSelector` and even it's a regular property (not an Input).

**Comment by jelbourn** [comment]
Isn't it trivial, though, to just add it to [our migration data](https://github.com/angular/components/blob/0a4b5180d9e05ea9466964ed66df3417566b6a23/src/cdk/schematics/ng-update/data/property-names.ts)? I would still do it if it's not any major effort

**Comment by crisbeto** [comment]
Looks like we don't have the schematics set up for v9. I've set them up in https://github.com/angular/components/pull/17101.

**Comment by crisbeto** [comment]
Added schematics where possible.

**Comment by devversion** [comment]
@crisbeto We should be able to add `CDK_DROP_LIST_CONTAINER` to the `classNames` data. I know it's technically not a class, but IIRC that is actually just doing migration for identifiers (can verify in a test case). Same for `CdkDragConfig`.

We can also handle `distance parameter in DropListRef.drop is now required.` in the `method-calls-check` data.

**Comment by crisbeto** [comment]
Nice, added 👍. The only part I'm confused by is what the `invalidArgCounts.count` means. Is it supposed to be the number of required parameters?

**Comment by devversion** [comment]
Yeah, I was confused about that rule at some point as well (i did not author it), but I guess it will print the given message if the arguments length matches the `count` length. 

e.g. in that case you'd set it to the amount of params minus one (to match if the `distance` param is missing)

**Pull request merged**
