### PR TITLE
fix(material/autocomplete): disable Chrome's native autocomplete

### PR DESCRIPTION
**Pull request by mmalerba**

### CODE REVIEW

**Review by crisbeto — COMMENTED** [review]
Last time I looked into this, I was under the impression that Chrome uses the `autocomplete` attribute as the key when saving the value when a form is submitted so eventually people will have persisted state for `mat-off` too. The alternative is to generate a unique name every time, but I decided against it, because according MDN there is a limited set of accepted values and I didn't know if there would be any accessibility drawbacks. See https://developer.mozilla.org/en-US/docs/Web/HTML/Attributes/autocomplete

**Comment by andrewseguin** [comment]
Huh that's good info - it'd be odd for Chrome to start thinking "mat-off" values need to be stored together.

Sounds like a unique random name may be the best way to go then. I can't think of any a11y drawbacks

**Comment by mmalerba** [comment]
Hmm it looks like the link in my comment got messed up, I meant to link to this comment on the Chrome issue: https://bugs.chromium.org/p/chromium/issues/detail?id=468153#c164

Based on what they're saying there, it sounds like it should _not_ try to autofill if we don't use one of the accepted values:
> you can give it semantic meaning that makes sense relative to what you're asking for: e.g. autocomplete="new-user-street-address".  If Chrome encounters that, it won't try and autofill the field.

Maybe its worth trying a little experiment to see what actually happens

**Comment by mmalerba** [comment]
I put together a little demo: https://jsfiddle.net/2jwvsr5m/

If you put in some bogus values, press submit and then refresh you should notice that the first 2 boxes save the bogus info. The last one does not trigger either autofill or autocomplete. So it seems setting mat-off is a sound approach

**Review by crisbeto — APPROVED** [review]
Tried the linked example both against jsfiddle and the dev app to make sure that the iframe isn't messing with it. It seems to work so LGTM.

**Comment by wagnermaciel** [comment]
@mmalerba This causing ~100 targets to fail internally with `Error: Accessibility violations` and directs us to [this link](https://dequeuniversity.com/rules/axe/4.1/autocomplete-valid?application=axeAPI). Let me know if you'd like to take a look at the test failures yourself and I will ping you a link

**Comment by mmalerba** [comment]
Ok, it sounds like this is indeed problematic from an a11y perspective, closing. For some more details about this rule: https://act-rules.github.io/rules/73f2c2

**Pull request closed without merging**
