### PR TITLE
feat(cdk/coercion): add coercion for string arrays

### PR DESCRIPTION
**Pull request by annieyw**
redo of https://github.com/angular/components/pull/17523 because there are now too many merge conflicts to merge cleanly

### CODE REVIEW

**Review by crisbeto — APPROVED** [review]
LGTM, but the API goldens check is failing.

**Review by mmalerba — APPROVED** [review]
LGTM

**Comment by jelbourn** [comment]
@annieyw can you amend your commit to include the original PR author as a co-author?

**Comment by annieyw** [comment]
Original author signed cla on original PR.

**Pull request merged**
