### PR TITLE
fix(material/datepicker): VoiceOver reading out cell content twice

### PR DESCRIPTION
**Pull request by crisbeto**
Adds a workaround to address the issue where VoiceOver reads out the content of the cells twice.

### CODE REVIEW

**Comment by crisbeto** [comment]
Caretaker note: the changes in this PR are the optimal in terms of accessibility, but they have the potential to break tests where people were checking the `textContent` of calendar cells. There is an alternative approach that is backwards-compatible, but it offers a worse user experience. We should evaluate the approaches based on how difficult this is to land.

**Review by jelbourn — APPROVED** [review]
LGTM since this is an improvement over what's happening now, but I think we still have some more significant structural changes ahead of us to make the datepicker more usable (e.g., trying to move through the cells with VO navigation doesn't really work at all)

**Comment by crisbeto** [comment]
cc @zarend in case this overlaps with some of the datepicker work you've been doing.

**Review by zarend — APPROVED** [review]

**Comment by zarend** [comment]
Hmm, I just tested on master, and I can't reproduce VoiceOver reading out a cell content twice. This might have been fixed by #24171

**Comment by crisbeto** [comment]
Closing since it sounds like this was fixed.

**Pull request closed without merging**
