### PR TITLE
fix(overlay): Unable to create overlay container once it has been destroyed

### PR DESCRIPTION
**Pull request by dannydamianus**

### CODE REVIEW

**Comment by dannydamianus** [comment]
@googlebot I signed it!

**Comment by dannydamianus** [comment]
Yup, not the same ```OverlayContainer``` element, create a new one.

There is a checking inside ```getContainerElement()``` preventing it from being created. We need to create it again because is already destroyed.

**Comment by crisbeto** [comment]
I mean that there it shouldn't be possible for `getContainerElement` to be called again after the `OverlayContainer` has been destroyed so these changes won't do anything.

**Comment by dannydamianus** [comment]
Sorry my bad.

Perhaps there is a need to call it manually?

I guess my use case is a bit weird, I extended the ```_createContainer()``` to inject the container element to be inside my own component and on component destroyed, I call the extended service to execute ```ngOnDestroy()``` and manually set ```this._containerElement = null```.

**Pull request closed without merging**
