### PR TITLE
Fix wrong autocomplete-plain-input example (fixes #16327)

### LINKED ISSUE #16327: Missing example in autocomplete documentation
#### Documentation Feedback

The autocomplete documentation is missing the "Autocomplete on a custom input element" example.
missing_autocomplete_example

**Affected documentation page:** https://material.angular.io/components/autocomplete/overview#autocomplete-on-a-custom-input-element

### PR DESCRIPTION
**Pull request by alvaromartmart**
Fix for #16327

### CODE REVIEW

**Comment by alvaromartmart** [comment]
@googlebot I signed it!

**Comment by alvaromartmart** [comment]
@crisbeto I see...

I was trying to fix #16327. The example for "Autocomplete on a custom input element" is broken in the documentation, I opened the console and saw the error "Could not find example: autocomplete-plain-input".

I think it's because the example is declared as "plain-input-autocomplete" in the EXAMPLE_COMPONENTS object, while it is referred to as "autocomplete-plain-input" in the documentation markdown file https://github.com/angular/components/blob/master/src/material/autocomplete/autocomplete.md#L99
```md
<!-- example(autocomplete-plain-input) -->
```

I don't know which one is wrongly named, I can fix the reference instead and submit a new pull request.

**Comment by crisbeto** [comment]
If the reference is wrong, it should be fixed in the Markdown file. Also you can push your change to the same PR.

**Comment by alvaromartmart** [comment]
Done, thanks for the feedback

**Comment by crisbeto** [comment]
Sorry, I just double-checked and it looks like we have to generate the `example-module` file manually due to a build limitation. The issue here is that the name of the example component doesn't match it's selector. The proper fix would be to revert the changes in the readme and rename the example component from `PlainInputAutocompleteExample` to `AutocompletePlainInputExample` both in the `autocomplete-plain-input-example.ts` and the `example-module`.

**Pull request merged**
