### PR TITLE
fix(material/dialog): Use `align` as `@Input()` in `MatDialogActions`

### PR DESCRIPTION
**Pull request by PooSham**
Right now we're relying on css selectors `[align='center']` and `[align='end']` for aligning action buttons in the dialog. Relying on a non-standard attribute causes some issues, such as no self-documentation, no type checkings, more annoying data-binding syntax and errors from IDEs and text editors (notably, VS Code marks the align-attribute as red). 

This is the third continuation from this PR that failed to trigger CircleCI workflows, [here](https://github.com/angular/components/pull/24178)

Fixes [#18479](https://github.com/angular/components/issues/18479)

### CODE REVIEW

**Comment by PooSham** [comment]
Third time's the charm? @crisbeto

**Comment by devversion** [comment]
@PooSham CI did not run on this PR either (which I haven't seen on other PRs so far). Looking at https://app.circleci.com/pipelines/github/PooSham/components/6/workflows/245a29c6-0952-4161-9e81-8f243fb5ee15/jobs/6, I can see that our CircleCI pipeline is executed as part of your _fork_/personal account, and not through the Angular CircleCI account. This reminded me of an old issue in CircleCI where jobs did not run because users/team members followed their fork in the CirceCI app.

Can you please make sure to unfollow your `components` fork in the CircleCI app, and then maybe re-push? More context: https://support.circleci.com/hc/en-us/articles/360008097173-Why-aren-t-pull-requests-triggering-jobs-on-my-organization-

You can see the jobs running as part of your fork (incorrectly): https://app.circleci.com/pipelines/github/PooSham/components?filter=all.

**Comment by PooSham** [comment]
@devversion Fascinating! I created a CircleCI account when the first PR didn't pass because I didn't know what it was and I was curious. 

I have since then unfollowed the project, and now I have also disconnected my github account from it, stopped following all projects, changed the email to the one corresponding to the cla, and I have also created a support ticket to remove my account completely and everything associated with it. I hope some of those actions help.

**Comment by devversion** [comment]
@PooSham 😞 oh yeah, that is really frustrating. I wish we could help more, but I don't see anything in our setup that could cause this, also it's difficult to help as this seems specific to your CircleCI account. I hope you will hear back from CircleCI soon, and thanks for being so patient with this.

In the meanwhile, I can just copy your PR into my account (just to run CI), and once this PR is approved, we could merge this PR from my account (preserving your credits obviously).

**Comment by PooSham** [comment]
@devversion if disconnecting my github account didn't work, sure... that's a possibility.

**Comment by devversion** [comment]
I've already copied your PR into #24333 so that you can see the jobs.

**Review by crisbeto — APPROVED** [review]
LGTM

**Comment by crisbeto** [comment]
Caretaker note: for some reason we haven't been able to get CircleCI to. We've verified that the PR actually passes.

**Comment by PooSham** [comment]
@crisbeto devversion made a change to the WORKSPACE file in their branch. Should I merge that change into this branch?

**Comment by PooSham** [comment]
Eeeh I merged @devversion's branch into mine and now there are a bunch of unrelated changes. Did I do something wrong? Where are those changes from? @crisbeto

**Comment by PooSham** [comment]
Ok, should be synced with both master and devversion's branch now. I assigned you to re-approve, @crisbeto

**Comment by PooSham** [comment]
@crisbeto could you please reapprove?

**Review by crisbeto — APPROVED** [review]
LGTM

**Comment by devversion** [comment]
I can confirm that CI is still green with the latest changes in this PR: https://github.com/angular/components/pull/24333/commits/5c304aeecbab9178b01245212d11289216ec2586 (see CI status indicator on this commit)

**Comment by wagnermaciel** [comment]
@crisbeto This conflicts with 13.2.x. Can we change this to `target: minor`?

**Comment by crisbeto** [comment]
Changed.

**Pull request merged**
