### PR TITLE
feat(material-luxon-adapter): add option to set first day of week

### PR DESCRIPTION
**Pull request by JiriBalcar**
Add firstDayOfWeek option to be able to change first day of week behaviour through MAT_LUXON_DATE_ADAPTER_OPTIONS

### CODE REVIEW

**Review by crisbeto — APPROVED** [review]
LGTM

**Comment by JiriBalcar** [comment]
Hi @crisbeto,
is there anything needed from my side for merge? I see one pendign check ci/circleci: lint.

Thanks
Jiri

**Comment by crisbeto** [comment]
Can you try rebasing your PR? We were changing some of the build setup so that might be why Circle didn't pick it up.

**Comment by JiriBalcar** [comment]
OK I did the rebase.

**Comment by crisbeto** [comment]
It looks like the rebase got messed up since it includes 31 other commits. Can you try resubmitting the PR? Just ping me and I'll re-approve it.

**Pull request closed without merging**
