### PR TITLE
fix(material/button): capture the event and stop its propagation if the anchor is disabled

### LINKED ISSUE #19428: bug(MatButtonModule): Disabled mat-button with routerLink still works
#### Reproduction

The issue is reproduced on StackBlitz: https://stackblitz.com/edit/inactive-links-problem

Steps to reproduce:

1. Use the following code:
`<a mat-button routerLink="/foo" [disabled]="true">Foo</a>`

#### Expected Behavior

The button is visually disabled and clicking it does not activate the link.

#### Actual Behavior

The button is indeed visually disabled, but the link still works.

#### Environment

- Angular: 9.1.9
- CDK/Material: 9.2.4
- Browser(s): Chrome, Mozilla, Safari
- Operating System (e.g. Windows, macOS, Ubuntu): Windows, iOS

### PR DESCRIPTION
**Pull request by arturovt**
Fixes #19428

### CODE REVIEW

**Comment by arturovt** [comment]
@crisbeto if you have time to look at this one, do you know why that might fail on Firefox? This works as expected in Firefox in the real app, but fails in unit tests.

**Comment by crisbeto** [comment]
I haven't tried debugging it, but my guess is that it's down to event registration order. The problem with preventing events like this is that it only works if the button events are bound before the router link events, e.g. it could work for `<button mat-button routerLink`>, but not `<button routerLink mat-button>`.

**Comment by arturovt** [comment]
> I haven't tried debugging it, but my guess is that it's down to event registration order. The problem with preventing events like this is that it only works if the button events are bound before the router link events, e.g. it could work for `<button mat-button routerLink>`, but not `<button routerLink mat-button>`.

Well, I checked that with router link in the real app and it works as expected, I mean the event is captured and the navigation isn’t started. This also passes in chromium unit tests.

**Comment by andrewseguin** [comment]
@crisbeto Is this change worth making at least so that it works in browsers other than Firefox? We could make the test skip for Firefox and leave a comment explaining why. 

Personally I dont like that some attribute works in a partial set of browsers, so I'd lean towards just documenting that disabling an anchor tag is for aesthetics and the client should make sure the route is not taken if disabled.

**Comment by crisbeto** [comment]
I'd rather avoid things that only work in some browsers, especially for something as fundamental as whether a link can be clicked.

**Comment by andrewseguin** [comment]
Closing since the behavior will be inconsistent between browsers

**Pull request closed without merging**
