### PR TITLE
fix(google-maps): typo in retina methods

### LINKED ISSUE #21418: bug(map-market-cluster): Typos + import @googlemaps/marketclusterplus
I found some typos in MapMarketClusterer :
- `getEnableRetinalIcons` should be `getEnableRetinaIcons` (without "l"). [here](https://github.com/angular/components/blob/master/src/google-maps/map-marker-clusterer/map-marker-clusterer.ts#L273)
- `setEnableRetinalIcons` should be `setEnableRetinaIcons` (without "l"). [here](https://github.com/angular/components/blob/master/src/google-maps/map-marker-clusterer/map-marker-clusterer.ts#L452)

Also I would definitely recommend to directly import the lib `@googlemaps/markerclustererplus` in the component. It would avoid this kind of typos and would improve devX.
It could be an `optionalDependencies` and have its own module to avoid errors when importing the `GoogleMapsModule`

### PR DESCRIPTION
**Pull request by crisbeto**
Fixes a couple of typos in the names of methods in the marker clusterer.

Fixes #21418.

**Note:** this isn't a breaking change, because the code that introduced the typo hasn't been released yet.

cc @mbehrlich

### CODE REVIEW

**Review by josephperrott — APPROVED** [review]
LGTM

**Review by Splaktar — APPROVED** [review]
LGTM and seems to align with https://googlemaps.github.io/js-markerclustererplus/classes/markerclusterer.html

**Comment by mbehrlich** [comment]
Good catch!

**Review by jelbourn — APPROVED** [review]
LGTM

**Pull request merged**
