### PR TITLE
build: add test/... to the bazel_build job

### PR DESCRIPTION
**Pull request by wagnermaciel**
* update the bazel_build job (the job that tests that everything
  builds with Bazel) to also include test/...

### CODE REVIEW

**Comment by wagnermaciel** [comment]
Blocked by PR #20221

**Comment by devversion** [comment]
@wagnermaciel looks like the job fails for some reason. Can you look into it? Happy to help if needed. I wonder how this runs in g3 right now?

**Comment by wagnermaciel** [comment]
> @wagnermaciel looks like the job fails for some reason. Can you look into it? Happy to help if needed. I wonder how this runs in g3 right now?

@devversion I could actually use some help here. When I build `//test/...` locally everything passes, but on CI the test is failing saying it
```
could not resolve //src/material-experimental/mdc-theming/prebuilt/indigo-pink.css
```

I remember Jeremy was surprised that we are able to reference `indigo-pink.css` in the benchmark components like this
`styleUrls: ['//src/material-experimental/mdc-theming/prebuilt/indigo-pink.css'],`
so I am pretty sure referencing indigo-pink like this is what's causing the failures but I don't know why.

**Comment by devversion** [comment]
@wagnermaciel yeah, that was actually something [I was not sure either](https://github.com/angular/components/pull/19320#discussion_r435482458). I looked into it.. and it seemed that this purely worked by _accident_ in `ngtsc`. See [explanation of why this works](https://github.com/angular/components/pull/19320#discussion_r435515440). As a side note: It would be good to consider moving away from this unconventional pattern at some point.

Can you try adding the prebuilt theme to `ng_assets` of the component benchmark rule? I see it is only added to `styles`, but we load the prebuilt theme as part of the component, so it needs to be part of the dependencies when the `ng_module` is built. This might also explain why it surfaces only on CI where we build in remote build containers (with full sandboxed environments).

**Comment by devversion** [comment]
I tried locally but was not able to reproduce it there. I'm pretty confident it's due to the issue I mentioned before w/ RBE. We can remove the prebuilt theme from the `styles` too because they are inlined directly into the component definition when the `ng_module` target is built.

**Comment by wagnermaciel** [comment]
@devversion I tried using `ng_assets` to provide the styles but the tests still failed to build on ci

I think we'll have to solve the larger problem and revisit this. Even though the current `component_benchmark` implementation is nice and simple, I agree that this not a good pattern and a more complex solution is clearly needed

I'm not sure if or when asset injection will be implemented given how many other higher priority tasks we've got lined up but how would you feel about discussing it again in next weeks team meeting?

**Comment by devversion** [comment]
@wagnermaciel Yeah. I'm not sure why it works locally but not on CI. The only difference is really the remote container sandboxing as far as I remember. Agreed, that we should not bother with this as obviously this is working by accident/is somewhat hacky.

**Pull request closed without merging**
