### PR TITLE
build: update checksum for io_bazel_rules_sass

### PR DESCRIPTION
**Pull request by zarend**

### CODE REVIEW

**Review by josephperrott — CHANGES_REQUESTED** [review]
This shouldn't have changed.  Do we know why this sha is different all of the sudden?

**Comment by zarend** [comment]
I do not know. I'm getting a crash about checksum mismatch on both my mac machine and linux machine.

```
Error in download_and_extract: java.io.IOException: Error downloading [https://github.com/bazelbuild/rules_sass/archive/1.49.4.zip] to /usr/local/google/home/zachzach/.cache/bazel/_bazel_zachzach/b2d336703fb3d3f93dae8817b6fd6b36/external/io_bazel_rules_sass/temp8489840885666228383/1.49.4.zip: Checksum was bfb89ca97a4ad452ca5f623dfde23d2a5f3a848a97478d715881b69b4767d3bb but wanted 68b58c69cda77c4f765be92cf076400d882ea2f10d66eaf369ed69409afab5be
ERROR: no such package '@io_bazel_rules_sass//': java.io.IOException: Error downloading [https://github.com/bazelbuild/rules_sass/archive/1.49.4.zip] to /usr/local/google/home/zachzach/.cache/bazel/_bazel_zachzach/b2d336703fb3d3f93dae8817b6fd6b36/external/io_bazel_rules_sass/temp8489840885666228383/1.49.4.zip: Checksum was bfb89ca97a4ad452ca5f623dfde23d2a5f3a848a97478d715881b69b4767d3bb but wanted 68b58c69cda77c4f765be92cf076400d882ea2f10d66eaf369ed69409afab5be
```

#24331 looks related to this

**Comment by zarend** [comment]
What's also interesting is that the same error message happens to me as on CI on master https://app.circleci.com/pipelines/github/angular/components/34387/workflows/c677915b-5128-453b-8765-6604d26bbcc2/jobs/339673

**Review by josephperrott — APPROVED** [review]
LGTM

We should keep an eye on this, because the sha's shouldn't change.

**Review by devversion — APPROVED** [review]
LGTM. SHAs changing all day today.. have looked into it quite some time already..

**Pull request merged**
