### PR TITLE
feat: expand input types with coercion to work with ngtsc input type checking

### PR DESCRIPTION
**Pull request by devversion**
Related to #17495

### CODE REVIEW

**Comment by devversion** [comment]
Blocked on:

* https://github.com/angular/angular/issues/33452. We can workaround this and patch `@angular/bazel` in the meanwhile
* https://github.com/angular/angular/issues/33451. We could disable `strictMetadataEmit` for the legacy build. This opens up the other question: why is this not enabled within Bazel?
* `NgModel` has an input called `disabled` that conflicts with the coerced `disabled` input if used on the same element. e.g. `<mat-slider disabled ngModel>`

**Comment by andrewseguin** [comment]
Needs rebase

**Comment by devversion** [comment]
@andrewseguin Rebased. I had to fix a couple of newly introduced coercion inputs, so I think as soon as this is green, it would be nice to merge it.

**Comment by manklu** [comment]
There is still a problem with async pipe:
```
TS2326: Types of property 'opened' are incompatible.
  Type 'boolean | null' is not assignable to type 'string | boolean | undefined'.
```

**Pull request merged**
