### PR TITLE
feat(material/list): allowDeselect option on mat-selection-list

### LINKED ISSUE #20036: feat(mat-selection-list): Allow deselecting elements when multiple=False
#### Feature Description

I'd like to have a mat-selection-list where up to one element can be selected. Currently the list when multiple is set to false, the list can start with no selection, but as soon as an item is selected it will always have exactly one selection. I'd like to propose adding another toggle which controls if items can be deselected or not.

I can easily write up the trivial code here, I'm just not sure what an acceptable name for the property would be. allowToggling could work, but it might be confusing for the multiple selection lists where presumably it shouldn't take effect.

### PR DESCRIPTION
**Pull request by ukrukarg**
Adds a new input [allowDeselect] that will allow an option to be deselected
for a single selection mat-selection-list. Defaults to current behavior.

Fixes #20036

### CODE REVIEW

**Comment by mmalerba** [comment]
I'm not sure this is a feature we want to add since it goes against the expected accessibility interaction for a single selection list.

\+ @jelbourn @zarend, our a11y experts in case they have any thoughts

**Comment by ukrukarg** [comment]
I run global TAB presubmit on a CL that allows deselection by default and nothing failed. So at least in google we should be safe to change the default behavior.

As for selection indicator: The issue that selection is only communicated by the background color is a preexisting issue, that is not introduced or made worse by this proposal. It is happening today for selection (the visual feedback that you've actually selected the item is pretty poor, because hover state and selection state are so similar.) I would still argue that those issues are orthogonal and it's not required to fix both of them at the same time in this PR.

**Comment by mmalerba** [comment]
Allowing deselection by default seems unexpected to me. If you look at all of the wc3 single selection listbox examples, they do not allow deselection and neither does the native select (technically a combobox, but the listbox part of it does not allow deselection).

**Comment by mmalerba** [comment]
After discussing this with some a11y experts, we concluded that this pattern would likely be unexpected & confusing to screen reader users. Better patterns for this use case would be an option representing nothing selected, a button to reset the selection, or potentially a different interaction pattern entirely (depending on the particular use case). Given that conclusion, I'm going to close this PR

**Pull request closed without merging**
