### PR TITLE
Switch datepicker to MDC

### PR DESCRIPTION
**Pull request by crisbeto**
Switches the Material datepicker to be based on top of the MDC components.

### CODE REVIEW

**Review by mmalerba — APPROVED** [review]
LGTM

**Review by mmalerba — CHANGES_REQUESTED** [review]
I realized that there's a potential issue with this. If we just switch it to the MDC version, people might not have the appropriate theme in their app.

We'll have to figure out how we want to handle this, here's a few ideas:
- Split out a legacy-datepicker that retains the legacy deps
- Have `ng update` automatically add the button theme when people update to v15
- Have the datepicker theme mixins @include the button one
- Have some back-compat mixin that `ng update` adds and `ng generate` removes after migrating the button:
  ```
  @mixin datepicker-back-compat-theme($theme) {
    .mat-datepicker {
      @include mat.button-theme($theme);
    }
  }
  ```

**Comment by crisbeto** [comment]
This is ready to review again. I've added a `material/legacy-datepicker` entrypoint with the minimum amount of code necessary to support it.

**Comment by crisbeto** [comment]
Closing in favor of https://github.com/angular/components/pull/25648.

**Pull request closed without merging**
