### PR TITLE
build: update angular shared dev-infra code

### PR DESCRIPTION
**Pull request by devversion**
It conflicted because we updated to v16 in `main` but not in `15.2.x`. Ideally the update would land in patch too, to avoid such conflicts, but that's a discussion where we never got a good conclusion on.

In framework I think we are updating devkit/AIO deps also for the patch branch, always following the `@next` NPM tag. Any thoughts here @crisbeto? (notice how dev-infra already uses v16 too- so we have a mismatch now)

### CODE REVIEW

**Comment by crisbeto** [comment]
We could cherry-pick the v16 update to the 15.2.x branch as well, as long as it doesn't affect the peer dependency in the package.json that is published to npm (I don't think it does). I'm also okay with just merging this change, but I could imagine it coming up again.

**Comment by devversion** [comment]
@crisbeto Updated to cherry-pick v16 update, so the dev-infra update just applies cleanly (and future updates 👍 )

**Comment by devversion** [comment]
hmm. I think we would use this version of Angular for the partial compilation output. I don't fully recall how this would affect our compatibility, but as long as partial compilation output is still backwards compatible (which seems to be the case), we should be good. Also the partial compilation output has a `minVersion` IIRC.

**Review by crisbeto — APPROVED** [review]

**Comment by devversion** [comment]
I've discussed with Alan as well a bit. Capturing the conclusion here: It's more correct to _not_ update v16 in the patch branch.

**Positives**:
* No diff between patch + main. Easier Renovate updates

Downsides
* Changes landing in patch, might break in v15. e.g. update recorder changes like #26700
* Library support guarantees: If library is built with M (major segment), then it supports `M`, `M+1` guaranteed. Not `M-1`

Long-term solution would be to run Renovate on both `patch` + `main`. I will revert back to be on the safe side for now.

**Review by alan-agius4 — APPROVED** [review]

**Pull request merged**
