### PR TITLE
feat(material/core/datetime): improve date parsing in the NativeDateAdapter

### PR DESCRIPTION
**Pull request by wartab**
Improve date parsing by being more permissive than JavaScript's Date.parse() and taking the supplied locale into account.

This partially addresses the issue https://github.com/angular/components/issues/27412 and should make the NativeDateAdapter become significantly more useful, especially for non English locales.

There are enivetably some tradeoffs and opinionated approaches here.

The following tests have been added. I'm adding them here to show what has all been implemented:

```ts
  it('should parse strings when composed of unambiguous substrings', () => {
    expect(adapter.parse('01/01/2020')).toEqual(new Date(2020, JAN, 1));
    expect(adapter.parse('13/01/2020')).toEqual(new Date(2020, JAN, 13));
    expect(adapter.parse('01/13/2020')).toEqual(new Date(2020, JAN, 13));
    expect(adapter.parse('21 07 2020')).toEqual(new Date(2020, JUL, 21));
    expect(adapter.getValidDateOrNull(adapter.parse('30 02 2020'))).toBeNull();
  });

  it('should parse strings when composed of unambiguous substrings with locale', () => {
    adapter.setLocale('fr-BE');
    expect(adapter.parse('01 janvier 2020')).toEqual(new Date(2020, JAN, 1));
    expect(adapter.parse('mardi 21 juillet 2020')).toEqual(new Date(2020, JUL, 21));
    expect(adapter.parse('2020    21    décembre   ')).toEqual(new Date(2020, DEC, 21));
    expect(adapter.getValidDateOrNull(adapter.parse('30 février 2020'))).toBeNull();

    adapter.setLocale('en-US');
    expect(adapter.parse('01 january 2020')).toEqual(new Date(2020, JAN, 1));
    expect(adapter.parse('tuesday 21 july 2020')).toEqual(new Date(2020, JUL, 21));
    expect(adapter.parse('2020    21    december   ')).toEqual(new Date(2020, DEC, 21));
    expect(adapter.getValidDateOrNull(adapter.parse('30 february 2020'))).toBeNull();
    expect(adapter.getValidDateOrNull(adapter.parse('30th february 2020'))).toBeNull();
  });

  it('should parse strings and infer which component is a year if ambiguous based on locale', () => {
    adapter.setLocale('ja-JP');
    expect(adapter.parse('01-01-23')).toEqual(new Date(2001, JAN, 23));
    adapter.setLocale('fr-BE');
    expect(adapter.parse('01-01-23')).toEqual(new Date(2023, JAN, 1));
  });

  it('should accept parsing strings not supplying a year', () => {
    adapter.setLocale('fr-BE');

    const currentYear = new Date().getFullYear();

    expect(adapter.parse('0101')).toEqual(new Date(currentYear, JAN, 1));
    expect(adapter.parse('1301')).toEqual(new Date(currentYear, JAN, 13));
    expect(adapter.parse('0113')).toEqual(new Date(currentYear, JAN, 13));
    expect(adapter.parse('21/07')).toEqual(new Date(currentYear, JUL, 21));
    expect(adapter.parse('21 juillet')).toEqual(new Date(currentYear, JUL, 21));
    expect(adapter.parse('juillet 21')).toEqual(new Date(currentYear, JUL, 21));
    expect(adapter.parse('21 déc.')).toEqual(new Date(currentYear, DEC, 21));
    expect(adapter.parse('21 décembre')).toEqual(new Date(currentYear, DEC, 21));
    expect(adapter.getValidDateOrNull(adapter.parse('13/13'))).toBeNull();
  });

  it('should parse strings in a locale aware manner when ambiguous', () => {
    adapter.setLocale('fr-BE');
    expect(adapter.parse('01-02-2020')).toEqual(new Date(2020, FEB, 1));
    adapter.setLocale('en-US');
    expect(adapter.parse('01-02-2020')).toEqual(new Date(2020, JAN, 2));
  });
```

Feel free to tell me what doesn't please you with this solution.

One thing I know is that I could probably cache the results of `_getLocaleLongFormatOrder()` into a Map, but I wasn't sure if that's okay to do and if yes, if it is better to store it at the class level or in a const outside the class (which is what I would have done).

I also wasn't exactly sure what should be considered invalid and what should just be null, so feel free to correct me if needed.

@mmalerba Pinging you since you asked me to inform you about a PR :)

### CODE REVIEW

**Comment by wartab** [comment]
I am aware that this isn't amazing for languages like Korean, Chinese, or Japanese. They use different separators for text based dates and my lack of understanding of those languages makes it difficult for me to implement parsing correctly for text based dates. So for those languages, it would probably just end up saying the format isn't valid but still accept numeric dates with optional separators.

**Comment by wartab** [comment]
This date parser also lets people write the week day in first position. That day isn't being validated, but definitely could be.

**Comment by mmalerba** [comment]
My concern with this is that its adding a lot of date parsing logic to the library. The main reason for using the adapter approach is that it allows other libraries to handle the date logic, while we focus on the UI. This is probably more than we would want to be responsible for maintaining

**Comment by wartab** [comment]
I understand this and if I'm fair while improving our in-house solution to cover situations we don't have (we're EU centric and everyone just does ddmmyyyy), I realised there are many corner cases to think about, which made this much more complex than I anticipated. In fact, I believe this implementation goes further than for example the Luxon adapter provides (iirc you have to supply the formats you're accepting).

Our use case is just that we do no longer need the bloat that are third party libraries to handle cases that aren't that difficult to handle with the Intl API being available virtually everywhere. And from what I've seen in the past months, this is a very common shift.

At the end of the day, maybe the implementation I submitted goes too far to be maintable for you guys (**but note that I'm willing to take on any issue related to it**), but I think that the current naive implementation is effectively useless and counter-productive, as could be seen in the issue that sparked my interest in this contribution. It was a very simple and reasonable example, that can have one-day-off consequences. That's why I think some middleground needs to be found at least.

**Comment by mmalerba** [comment]
I agree that the `NativeDateAdapter` isn't particularly useful outside of demos / internal dashboards where everyone is fine with using the `en-US` locale. For apps that want to work with native `Date` objects but need more robust parsing support I would recommend the `material-date-fns-adapter`. It operates on native `Date` objects and the library is modular so doesn't add too much size bloat.

Since we don't want to bake in complex date logic, maybe the best thing to do would be log a warning in dev mode that the `NativeDateAdapter` isn't a robust solution and people may want to consider using a more fully featured `DateAdapter`?

I do think we could improve the `NativeDateAdatper` a bit by using [Angular's i18n API](https://github.com/angular/angular/blob/16.2.0/packages/common/src/i18n/format_date.ts) instead of `Intl.DateTimeFormat`, but that's still not  going to help with the parsing situation

**Comment by wartab** [comment]
Otherwise, what would you think about a much simpler implementation solely based on the current locale's short date format, with a fallback to the current Date.parse() implementation? This would still require to address the timezone bug, but it wouldn't be as long as my PR that tries to make sense of what a user might have meant.

**Comment by mmalerba** [comment]
The simpler approach sounds small enough that we can probably add it 👍

**Comment by wartab** [comment]
Sorry about the delay, I was on vacation until recently, so I'll work on this this weekend.

**Pull request closed without merging**
