### PR TITLE
fix(sort): If there is no direction, setting active as empty #15169

### LINKED ISSUE #15169: [Sort] If there is no direction, active should not be populated with a sortable ID
After cycling through the sort options, if a sortable's direction becomes empty (`''`) then `MatSort`'s `this.active` should revert to an empty string or undefined again.

### PR DESCRIPTION
**Pull request by Suresh918**
Fixes #15169

### CODE REVIEW

**Comment by Suresh918** [comment]
@andrewseguin Updated the JS doc. Can you please check.
Are there any ways to chat in private to discuss doubts ?

**Comment by andrewseguin** [comment]
Cool thanks

Feel free to chat over the PR, it's nice for us to keep things documented for future reference. Would be happy to hear your thoughts/doubts on this

**Comment by Suresh918** [comment]
@andrewseguin When this pull request will be merged?

**Comment by andrewseguin** [comment]
Unfortunately it takes a good amount of time to get changes in due to the myriad of tests that need to pass internally. I'll move this up to P2 to help prioritize it.

**Comment by Suresh918** [comment]
@andrewseguin  I created a new pull request for this with the same changes 
[](https://github.com/angular/components/pull/22027)
as it is difficult to rebase as there are changes in the folders from the instant this merge request was created.

**Pull request closed without merging**
