### PR TITLE
docs(material/snack-bar): update docs & examples for MDC-based snackbar

### PR DESCRIPTION
**Pull request by mmalerba**

### CODE REVIEW

**Review by crisbeto — APPROVED** [review]
LGTM. Is the dev app demo going to be handled in a separate PR?

**Comment by mmalerba** [comment]
what needs to happen for the dev-app? I think it already has demos for both legacy & MDC versions

**Comment by crisbeto** [comment]
The files of the legacy one should be prefixed with `legacy-`, the class names should be changed to `Legacy*` and the route should be renamed to `/legacy-snackbar`. Also the MDC one should be changed to remove the MDC prefix.

**Comment by mmalerba** [comment]
Ok, dev-app updated

**Pull request merged**
