### PR TITLE
Import Statement Added

### PR DESCRIPTION
**Pull request by abhinav-goyall**
It would be good if we provide user the information on how to use BrowserAnimationsModule in the angular app. Adding import staement syntax and other change required in the app.module.ts file.

### CODE REVIEW

**Comment by abhinav-goyall** [comment]
@googlebot I signed it!

**Comment by abhinav-goyall** [comment]
Could you please review my pull request?

**Comment by jelbourn** [comment]
Thanks for the proposal! At this time we want to keep the getting-started guide pretty short/concise, assuming that most people will either use the `ng add` schematic to add this, or be familiar enough with Angular that importing an `NgModule` would be straightforward.

**Comment by abhinav-goyall** [comment]
Thanks for the review.

**Pull request closed without merging**
