### PR TITLE
minor fix for cdk-tree-flat-sample

### PR DESCRIPTION
**Pull request by salour**
current behavior can be seen here: https://material.angular.io/cdk/tree/overview

----parent-node
-----------------child-node
---------------------------grandchild-node

with current example code, when you have an expanded paren-node and expanded child-node( with children), then if you collapse grandparent node, it hides the child-node without hiding grandchild. the grandchild will be hanging of no-where.

### CODE REVIEW

**Comment by salour** [comment]
I signed it!

**Comment by jelbourn** [comment]
Looks like there's a build failure on the CI here

**Comment by andrewseguin** [comment]
Needs rebase

**Comment by mmalerba** [comment]
It looks like this was fixed in https://github.com/angular/components/pull/20683

**Pull request closed without merging**
