### PR TITLE
update on docs and comments for default option value for checkbox

### LINKED ISSUE #21025: docs-bug(checkbox): Documentation use "MAT_CHECKBOX_CLICK_ACTION" without notification of deprecation. When MAT_CHECKBOX_DEFAULT_OPTIONS should be used. Errors in v11.
The checkbox documentation page has a section about the usage of "MAT_CHECKBOX_CLICK_ACTION" to define the behavior on clicks. 
It didn't provide any indication that this method is deprecated, nor that it was replaced with  ```{provide: MAT_CHECKBOX_DEFAULT_OPTIONS, useValue: { clickAction: 'noop' } as MatCheckboxDefaultOptions }```

Running a project after upgrading the Angular and Material package will produce an error.

Migration didn't touch this. I don't know if it was updated in earlier migration, since I've only added the provider a week ago, into v10 project. (no notice of deprecation anywhere I saw)

**Affected documentation page:** 
https://material.angular.io/components/checkbox/overview

### PR DESCRIPTION
**Pull request by adhispace**
updates the documentation and comments of customizing the default option of the checkbox.
the default option value to provide for checkbox is MAT_CHECKBOX_DEFAULT_OPTIONS for version>=10

fixes #21025

### CODE REVIEW

**Comment by adhispace** [comment]
Hi

this PR has changes as same as the below one
https://github.com/angular/components/pull/21226

I closed the PR #21226 as I faced difficulty in resolving circleci build error as this is my first ever PR. sorry for the trouble.
kindly review.

thanks

**Review by crisbeto — APPROVED** [review]
LGTM

**Comment by crisbeto** [comment]
Caretaker note: for some reason the CI didn't run on this PR. It's only doc changes so I think that we can merge it anyway.

**Review by wagnermaciel — APPROVED** [review]
lgtm

**Comment by jelbourn** [comment]
@adhispace do you happen to have CircleCI set up on your fork of angular/components?

**Comment by wagnermaciel** [comment]
Seems like this change has conflicts with 11.0.x. Is it ok to change this to `target: minor`?

**Comment by adhispace** [comment]
> @adhispace do you happen to have CircleCI set up on your fork of angular/components?

no, I dont have CircleCI setup in my fork.

**Pull request merged**
