### PR TITLE
fix(material/paginator): fix issue with paginator focus

### PR DESCRIPTION
**Pull request by DBowen33**
Fixes an issue where focus is lost and goes back to the body when on the next, previous, first, or last buttons are disabled. Changed to where focus will now jump to the next appropriate button instead of focusing to body.

Before:
[Screen recording 2024-05-07 9.22.24 AM.webm](https://github.com/angular/components/assets/42016383/5a71521f-ae34-4faa-b812-233d9a609a9d)

After: 
[Screen recording 2024-05-07 9.19.26 AM.webm](https://github.com/angular/components/assets/42016383/21f877a4-d836-4f3f-9282-14bfd4c4c20e)

Fixes b/286098030

### CODE REVIEW

**Comment by andrewseguin** [comment]
This doesn't seem to capture the case of activating the button via other keypresses or clicks. It's also fragile depending on a 100ms delay to check whether the button becomes disabled and moving focus. Using `afterNextRender` would be more stable

It'd be nice if there was more intelligence in the paginator to know that a button has focus, but is about to lose focus so that it can directly move it. Right now it seems this change will see the focus move from the button, then to the body temporarily, then to another button.

**Comment by andrewseguin** [comment]
How about adding a `(blur)` listener on the buttons that can check whether they are now disabled? If so, move focus to another element [that isn't disabled]

**Comment by andrewseguin** [comment]
Another alternative is just to set `disabledInteractive` on the buttons, which lets them remain focusable after they become disabled

**Comment by crisbeto** [comment]
Looks like this is resolved by #29379.

**Pull request closed without merging**
