### PR TITLE
build: use ts-api-guardian from npm

### PR DESCRIPTION
**Pull request by alan-agius4**

### CODE REVIEW

**Comment by alan-agius4** [comment]
Blocked by https://github.com/angular/angular/pull/30051

**Comment by alan-agius4** [comment]
//cc @mmalerba & @devversion

**Comment by mmalerba** [comment]
This PR was included in https://github.com/angular/components/pull/15909

**Comment by devversion** [comment]
Oh right :smile: Interesting that it didn't show any conflicts/rebase message.

**Pull request closed without merging**
