### PR TITLE
Revert "feat(cdk/testing): add the ability to dispatch arbitrary even…

### PR DESCRIPTION
**Pull request by wagnermaciel**
…ts (#20714)"

This reverts commit b7cfe673708fc99226f00da57785751764460b68.

### CODE REVIEW

**Comment by crisbeto** [comment]
What's the reason behind reverting it?

**Comment by wagnermaciel** [comment]
Breaks ~220 targets and is holding up a sync. I'm trying to debug it now to see if I can avoid having to start a sync all over again

**Comment by crisbeto** [comment]
I'm not sure how it could break something, because it adds a new optional member to an interface which is only being called inside of our own tests.

**Comment by wagnermaciel** [comment]
I fixed the issue. The problem is dispatchEvent isn't declared on ElementFinder. I was getting an error that said:
```
The type has a string index signature, but it is being accessed using a dotted property access. 
```

So I had to change `element.dispatchEvent(event)` to `element['dispatchEvent'](event)` for now.

A more basic example of this would be:

> let x: {[key: string]: string} = {};
> x['foo'] = 3;  // ok
> console.log(x.foo);  // error

**Pull request closed without merging**
