### PR TITLE
docs: fix typo in css file

### PR DESCRIPTION
**Pull request by aanchal88**

### CODE REVIEW

**Review by crisbeto — APPROVED** [review]
LGTM

**Review by crisbeto — DISMISSED** [review]
Actually this also needs to be fixed in `src/material/core/typography/_versioning.scss`.

**Comment by Andrashynets** [comment]
пт 8. 9. 2023 о 11:59 Kristiyan Kostadinov ***@***.***> пише:

**Comment by aanchal88** [comment]
Hii @crisbeto , Done with the changes please review.

**Review by mmalerba — APPROVED** [review]

**Pull request merged**
