### PR TITLE
Maps update

### PR DESCRIPTION
**Pull request by mbehrlich**
Moves recent changes from master into google-maps-next, so that new components can be altered to use the NgZone fix from pull request 18034

### CODE REVIEW

**Comment by jelbourn** [comment]
I think you probably want to rebase your branch on top of master rather than bringing in all the commits

**Comment by mbehrlich** [comment]
> I think you probably want to rebase your branch on top of master rather than bringing in all the commits

Discussed offline. That is what I did here, it adds a bunch of commits because google-maps-next is a bit behind master.

**Comment by mbehrlich** [comment]
> A Googler has manually verified that the CLAs look good.
> 
> (Googler, please make sure the reason for overriding the CLA status is clearly documented in these comments.)
> 
>  **Googlers: [Go here](https://goto.google.com/prinfo/https%3A%2F%2Fgithub.com%2Fangular%2Fcomponents%2Fpull%2F18358) for more info**.

All of these commits are already in master except for by new google-maps related commits. I wrote those, and I accepted the cla.

**Comment by jelbourn** [comment]
Closing in favor of #18485

**Pull request closed without merging**
