### PR TITLE
fix(form-field): Displaying of mat-hint in combination with *ngIf

### LINKED ISSUE #9747: mat-hint not animated when showed for first time on condition
#### Bug, feature request, or proposal:

Maybe a bug, definitely a feature

#### What is the expected behavior?

When I put a condition on the `mat-hint` element (for instance, show it only if a character has been typed), the element should be animated and slide in from the input.

#### What is the current behavior?

At first, the element isn't animated. Until a `mat-error` is shown, the element won't be animated. 

#### What are the steps to reproduce?

[Stackblitz](https://stackblitz.com/edit/angular-material-with-angular-v5-vlqdic?file=app/app.component.html)

### PR DESCRIPTION
**Pull request by dariobraun**
Fixes #9747
Closes #12859

### CODE REVIEW

**Comment by dariobraun** [comment]
@andrewseguin any feedback on this?

**Comment by dariobraun** [comment]
@andrewseguin is this still relevant?

**Comment by mmalerba** [comment]
@dariobraun I've rebased this for you and cleaned up some of the lint issues, but there's still failing tests on CI that will need to be fixed before this can go in

**Comment by mmalerba** [comment]
Closing since this fix is for the legacy mat-form-field which has been superseded by the MDC based one.

**Pull request closed without merging**
