### PR TITLE
 fix(sort): display mat-sort-header arrow when sorting programmatically

### PR DESCRIPTION
**Pull request by adgoncal**
Fix mat-sort-header arrow not displaying after sorting programmatically (eg. `matSort.sort()`)

Related to #10242, #12754

### CODE REVIEW

**Comment by jelbourn** [comment]
@andrewseguin can you review?

**Comment by andrewseguin** [comment]
My apologies for the late review, we should have checked this out sooner. Thanks for making this pull request, everything looks great.

The only nit I see with this implementation is that there is no animation when sort is activated programatically. It looks like the arrow just appears. This also comes up when you cycle through a header's sort state (active -> asc -> desc -> inactive -> active). The second active does not show an animation, but just appears without floating in.

These are minor issues and I'd rather see this fix go in even if it means a small regression in animations.

If you get some time, could you take a look into see if you can resolve this small issue? If not, let's go ahead and get this merged.

Thanks again for the PR

**Comment by molayodecker** [comment]
Can you please fix circle so that this PR can be merged? @andrewseguin @leduyminh48

**Comment by adgoncal** [comment]
@andrewseguin: I don't think I will have the time to look into the animations issue in the near future.

**Comment by swseverance** [comment]
@andrewseguin @leduyminh48 any idea when this PR will be merged? It's been outstanding for awhile. Thank you

**Comment by adgoncal** [comment]
```
Unexpected value 'MatFormFieldModule in /b/f/w/bazel-out/k8-fastbuild/bin/src/material/form-field/form-field-module.d.ts' imported by the module 'TableExamplesModule in /b/f/w/src/material-examples/material/table/module.ts'. Please add a @NgModule annotation.

Unexpected value 'MatSelectModule in /b/f/w/bazel-out/k8-fastbuild/bin/src/material/select/select-module.d.ts' imported by the module 'TableExamplesModule in /b/f/w/src/material-examples/material/table/module.ts'. Please add a @NgModule annotation.
```

Why is it unexpected? It is just a regular module import. This error tells me nothing useful.

@jelbourn, @andrewseguin I don't have time to debug this. This PR has been open for almost a whole year now. If you have any intention of fixing this bug, please take over from here. Otherwise, feel free to close this PR.

**Comment by andrewseguin** [comment]
This should be captured by https://github.com/angular/components/pull/19492

**Pull request closed without merging**
