### PR TITLE
refactor(material-experimental/mdc-paginator): clean up theme sass

### PR DESCRIPTION
**Pull request by mmalerba**

### CODE REVIEW

**Review by crisbeto — COMMENTED** [review]
What exactly is broken in the dark theme? It seems to be working in the dev app.

**Comment by mmalerba** [comment]
Hmm you're right, I migrated an internal app I made and it was broken there. I might need to look more into what the difference was between that app and our dev app. (Though even if this change isn't necessary I'd still like to submit it as it cleans up the theme code a bit. There's no reason to transform the mat color config to an MDC one if we're not passing it to MDC's mixins

**Comment by mmalerba** [comment]
It was something wrong with the live reload setup, did a fresh rebuild and it was fine. That said I do think this is valuable cleanup so leaving it open

**Comment by jelbourn** [comment]
@mmalerba could you amend the commit to be more specific about the nature of the cleanup?

**Comment by crisbeto** [comment]
From what I can see, the change here is that we go through our own theming APIs instead of MDC's. I wrote the theme this way, because I was under the impression that we wanted to stick to MDC's theming API for the MDC-based components. We've been following a similar setup for all of the other ones under `material-experimental`.

**Comment by mmalerba** [comment]
We still want to rely on our themeing system, the `mat-using-mdc-theme` mixin temporarily plugs values from our theme into MDC's global variables. We only need to use that when we're calling out to MDC's mixins. Eventually I hope to get rid of it entirely, since MDC is moving toward a system that looks more like ours - one where you pass config objects around rather than rely on global variables

**Comment by mmalerba** [comment]
updated the commit message with more info

**Review by jelbourn — APPROVED** [review]
LGTM

**Pull request merged**
