### PR TITLE
build: use specific MDC version

### PR DESCRIPTION
**Pull request by crisbeto**
Our MDC version requirement currently uses a caret with the intention of allowing any version after the specified canary. This isn't actually how npm works and it can end up installing an earlier version. The version isn't technically valid semver, causing the package manager to sort the versions alphabetically and to pick the last one. This behavior threw me off when rebasing #22504 yesterday, because it ended up installing a version that was too old.

These changes lock us to a specific version.

### CODE REVIEW

**Review by devversion — APPROVED** [review]
LGTM.

**Review by jelbourn — APPROVED** [review]
LGTM

**Comment by andrewseguin** [comment]
Please rebase

**Comment by crisbeto** [comment]
Rebased.

**Pull request merged**
