### PR TITLE
fix(material/core): add set centered with class mat-ripple-centered

### PR DESCRIPTION
**Pull request by ThonyBat**
you have setting unbounded with class but not same with centered so added

### CODE REVIEW

**Comment by ThonyBat** [comment]
> @googlebot I signed it!

**Comment by ThonyBat** [comment]
@googlebot I fixed it.

**Comment by ThonyBat** [comment]
@googlebot I fixed it.

**Review by devversion — COMMENTED** [review]
Thanks for this PR. We intentionally didn't add this class because there are no CSS styles required to center ripples, while for the `unbounded` option, CSS styles are required.

Is there any specific use case that would require the `mat-ripple-centered` class?

**Comment by ThonyBat** [comment]
Thanks for your feedback
Effectively you don't use it, it could be useful if the developer adds a class dynamically.
I would like to use it to have this effect on <div> zones which have a condition of appearance of the class because the centering is not systematic

**Comment by andrewseguin** [comment]
We'll close this out since we'd prefer not adding an extra class that doesn't provide any styles. Looks like you may be able to achieve the effect from your client code

**Pull request closed without merging**
