### PR TITLE
WIP feat(progress-container): add progress-container component

### LINKED ISSUE #13667: feat(mat-button): add progress-spinner option
#### Bug, feature request, or proposal:

Proposal

#### What is the expected behavior?

Allow for a properly-sized and positioned progress spinner to be triggered inside a `mat-button`, temporarily overriding its initial content

#### What is the current behavior?

No configuration available, can manually place and position a progress spinner inside a `mat-button`

#### What are the steps to reproduce?

This is a sample template thrown together (very unoptimized): https://stackblitz.com/edit/angular-material2-issue-qbjrmi?file=app%2Fapp.component.html

Click on `LOADING` to trigger the spinner

#### What is the use-case or motivation for changing an existing behavior?

Defined in the spec: https://material.io/design/components/progress-indicators.html#circular-progress-indicators under “Integrating with actions”

#### Is there anything else we should know?

Probably needs an a11y review since the content of the button will change

### PR DESCRIPTION
**Pull request by CaerusKaru**
* Add two new components: `mat-progress-container` and `mat-progress-content`
  for use with new directive `matProgress`
* When triggered, the `matProgress` directive will emit an event that notifies
  the components which will, if triggered to show the progress container, add
  that template to the view and hide the progress content, and otherwise remove
  the template from the view and show the progress content

Fixes #13667

### CODE REVIEW

**Comment by CaerusKaru** [comment]
Much thanks to @crisbeto for help with the design. The tests/docs are incomplete pending a final design review (a lot of the names, etc are bound to be changed).

**Comment by CaerusKaru** [comment]
Open design questions:
* Should this be in the CDK since it's a pretty agnostic container?
* Should the names be `container`/`content` like `sidenav`, or is it misleading?
* Is this the best approach?

**Comment by jpike88** [comment]
Has this been abandoned?

**Comment by angajime** [comment]
Any update on this? Is there something we can do to help?

**Comment by jelbourn** [comment]
We've decided not to move forward with this feature

**Pull request closed without merging**
