### PR TITLE
MDC table last row within tbody set bottom border as none for header …

### PR DESCRIPTION
**Pull request by prajapatimadan**
…cell as other mat-mdc-cell bottom border are set as none, this will make consistent layout for table.

Also referring "bug(material/table): last row border inconsistency #27731"

### CODE REVIEW

**Comment by prajapatimadan** [comment]
Please suggest any steps required to complete the review process, so that PR can approve.

**Review by prajapatimadan — COMMENTED** [review]
@andreroggeri , This CSS changes, will resolve the table layout consistency issue and not impact on any other table component functionalities. Please have look

**Comment by andreroggeri** [comment]
@prajapatimadan I believe you tagged the wrong person 😅

**Comment by prajapatimadan** [comment]
> @prajapatimadan I believe you tagged the wrong person 😅

Sorry!

**Review by andrewseguin — APPROVED** [review]

**Comment by andrewseguin** [comment]
Closing in favor of https://github.com/angular/components/pull/30193

**Pull request closed without merging**
