### PR TITLE
fix(platform): add new Edge tag.

### PR DESCRIPTION
**Pull request by Zcating**

### CODE REVIEW

**Comment by devversion** [comment]
Hey, thanks for this PR. What would be the use case for detecting the Chromium/Blink-based version of Edge? I think in the current implementation of `Platform` we always had detection for browsers/rendering engines which could require special treatment/behave differently.

**Comment by Zcating** [comment]
The platform codes use brand name as Tag, so that I though you maybe miss the newly Edge's tag when I audited the code.

**Comment by Zcating** [comment]
I maybe can close it, if you don't need to specify the brand of browser.

**Comment by jelbourn** [comment]
I think we'll probably leave this as-is for now and potentially revisit if we encounter issues that are exclusive to Chromium-based Edge.

**Pull request closed without merging**
