### PR TITLE
test(material-experimental/mdc-slider): add ngModel unit tests

### PR DESCRIPTION
**Pull request by wagnermaciel**

### CODE REVIEW

**Comment by wagnermaciel** [comment]
@mmalerba I haven't tried removing the custom control value accessor implementation for `MatSliderThumb`, yet. I'm going to add another commit for it. I'm just leaving this comment so you know I haven't forgotten 👍🏽

**Comment by wagnermaciel** [comment]
@mmalerba Ok, I went back and checked and it seems we have some custom logic for `setDisabledState`. Here's a link to an old conversation we had about it
https://github.com/angular/components/pull/22016#discussion_r583089116

**Review by crisbeto — APPROVED** [review]
LGTM

**Review by mmalerba — APPROVED** [review]
LGTM

**Pull request merged**
