### PR TITLE
fix(material-experimental/mdc-chips): unable to override role of chip option

### PR DESCRIPTION
**Pull request by crisbeto**
Fixes that the role wasn't being forwarded to the underlying button inside a `mat-chip-option`.

### CODE REVIEW

**Comment by crisbeto** [comment]
Blocked pending a refactor of an internal component.

**Comment by mmalerba** [comment]
@crisbeto is change still needed? is it still blocked?

**Comment by crisbeto** [comment]
It's blocked on an internal issue.

**Comment by crisbeto** [comment]
The internal issue that initially triggered this PR was closed so I'm closing the PR as well.

**Pull request closed without merging**
