### PR TITLE
fix(material/list): nav list item border-radius

### PR DESCRIPTION
**Pull request by wagnermaciel**
* https://m2.material.io/components/navigation-drawer#states
* https://m3.material.io/components/navigation-drawer/specs

### CODE REVIEW

**Review by crisbeto — APPROVED** [review]
The list change LGTM. I wonder if we don't need to make a change to either the inner padding of the list or the sidenav since it currently looks a bit weird because it's edge-to-edge 🤔

**Comment by wagnermaciel** [comment]
> The list change LGTM. I wonder if we don't need to make a change to either the inner padding of the list or the sidenav since it currently looks a bit weird because it's edge-to-edge 🤔

I was thinking this exactly. I think we do want this, but that change is probably so breaking that I'll want to do it in a separate PR 😭

Also, I never knew about that dev-app-preview label. That is awesome!

**Comment by crisbeto** [comment]
I think that if we scope it to only nav lists inside sidenavs on M3 it shouldn't be too breaking.

**Review by zarend — APPROVED** [review]

**Comment by karmasakshi** [comment]
I'm on M2 and this change has introduced border-radius to menu items. Is this expected? Screenshot from my local:

Screen Shot 2024-04-12 at 7 51 30 PM

**Comment by wagnermaciel** [comment]
@karmasakshi Hi Karma, yes this is intentional. Here's what the m2 nav list (or navigation drawer as Material Design calls it) is meant to look like

https://m2.material.io/components/navigation-drawer

**Comment by karmasakshi** [comment]
Thank you, I added an overall padding to `.mdc-list` instead of vertical only. Looks good.

Screen Shot 2024-04-12 at 8 01 51 PM

Screen Shot 2024-04-12 at 8 03 28 PM

**Pull request merged**
