### PR TITLE
refactor(material/theming): normalize config in all typography mixins for non-mdc components

### PR DESCRIPTION
**Pull request by mmalerba**
This is split off of #21778 which covers MDC conmponents as well

### CODE REVIEW

**Review by crisbeto — APPROVED** [review]
LGTM, but the CI is failing.

**Review by jelbourn — APPROVED** [review]
LGTM

**Comment by andrewseguin** [comment]
Needs rebase

**Comment by mmalerba** [comment]
@andrewseguin rebased

**Pull request merged**
