### PR TITLE
build: delete benchmarks

### PR DESCRIPTION
**Pull request by wagnermaciel**

### CODE REVIEW

**Review by devversion — APPROVED** [review]
@wagnermaciel Should we also delete the benchmark rule in dev-infra then? or what's the plan here? I do realize framework still has tests potentially using this

**Comment by wagnermaciel** [comment]
@devversion I'd have to check in with Jeremy or Miles but I think so

**Comment by devversion** [comment]
that would be great, thanks

**Comment by mmalerba** [comment]
I have no problems with killing the rule as well, its in the version history if we  ever need to bring it back

**Pull request closed without merging**
