### PR TITLE
feat(material-experimental/mdc-menu): support density

### PR DESCRIPTION
**Pull request by crisbeto**
Adds support for density to the MDC-based `mat-menu`.

### CODE REVIEW

**Comment by mmalerba** [comment]
@jelbourn Do you know if we want to change density of things in an overlay? I remember there being some discussion about not needing to do that, but also maybe it looks weird if the trigger is dense and the popup isnt?

**Comment by jelbourn** [comment]
https://material.io/design/layout/applying-density.html#usage
> Don’t increase the density of components that involve focused tasks, such as interacting with a dropdown menu or picker. Increasing density on components such as date pickers reduces usability by limiting tappable space.

**Comment by jelbourn** [comment]
That does seem to conflict with the menu spec. We should raise it to the Material folks

**Comment by mmalerba** [comment]
I added an agenda item for our next meeting with them. Will mark this as blocked pending their feedback

**Comment by jelbourn** [comment]
I filed a bug with the spec

**Comment by crisbeto** [comment]
Did we ever get an answer on this?

**Comment by crisbeto** [comment]
Closing this for now given how much the menu has changed since then and how out of date it is.

**Pull request closed without merging**
