### PR TITLE
build: stylelint not working correctly

### PR DESCRIPTION
**Pull request by crisbeto**
Recently we changed the names of some Stylelint rules, but the linter wasn't updated which leads to several warnings for each file that goes through it.

For reference, Stylelint logs the following on the CI as well, but we didn't notice because it exits with a non-error code.

```
src/material/core/theming/tests/test-theming-api.scss
 1:1  ×  Unknown rule function-url-scheme-disallowed-list         function-url-scheme-disallowed-list
 1:1  ×  Unknown rule unit-allowed-list                           unit-allowed-list
 1:1  ×  Unknown rule declaration-property-value-disallowed-list  declaration-property-value-disallowed-list

src/material/core/theming/tests/test-theming-bundle.scss
 1:1  ×  Unknown rule function-url-scheme-disallowed-list         function-url-scheme-disallowed-list
 1:1  ×  Unknown rule unit-allowed-list                           unit-allowed-list
 1:1  ×  Unknown rule declaration-property-value-disallowed-list  declaration-property-value-disallowed-list

src/cdk/schematics/ng-update/test-cases/misc/global-stylesheets-test.scss
 1:1  ×  Unknown rule function-url-scheme-disallowed-list         function-url-scheme-disallowed-list
 1:1  ×  Unknown rule unit-allowed-list                           unit-allowed-list
 1:1  ×  Unknown rule declaration-property-value-disallowed-list  declaration-property-value-disallowed-list
```

### CODE REVIEW

**Review by josephperrott — APPROVED** [review]
LGTM

We should also make this error exit with a non-zero code

**Comment by crisbeto** [comment]
I don't think we can do much about the exit code, it's just what Stylelint decided to exit with.

**Comment by josephperrott** [comment]
@crisbeto played with it for a second and found how the way to set it to fail if these things are found.  Pushed it up as a fixup.

**Comment by crisbeto** [comment]
Nice! I don't know whether we handle fixup commits in this repo though.

**Pull request merged**
