### PR TITLE
feat(module:overlay): directive support disposeOnNavigation

### PR DESCRIPTION
**Pull request by wzhudev**

### CODE REVIEW

**Comment by wendellhu95** [comment]
@googlebot I signed it!

**Comment by wendellhu95** [comment]
@crisbeto Please check this bug of ng-zorro https://github.com/NG-ZORRO/ng-zorro-antd/issues/1530 and this bug of components itself https://github.com/angular/components/issues/11478.

**Comment by crisbeto** [comment]
I don't see where the overlay directive is being used in the linked example.

**Comment by wendellhu95** [comment]
@crisbeto Sorry for the misleading.

Maerial seems just missing a property [here](https://github.com/angular/components/blob/68a2f89d5909e8138f567f39e3ba703dea91f111/src/material/tooltip/tooltip.ts#L402-L407).

But in ng-zorro-antd we use Overlay [in a declarative way](https://github.com/NG-ZORRO/ng-zorro-antd/blob/39487f154e5e69cb741d3249a8190664dccf9ad9/components/tooltip/nz-tooltip.component.html#L2-L13).

**Comment by crisbeto** [comment]
That was my point. Wouldn't that component that is used declaratively be destroyed when you navigate to a different route?

**Comment by wendellhu95** [comment]
> That was my point. Wouldn't that component that is used declaratively be destroyed when you navigate to a different route?

I am afraid not, according to the reproduction provided in https://github.com/NG-ZORRO/ng-zorro-antd/issues/1530.

**Comment by crisbeto** [comment]
This was done in #27672. Closing.

**Pull request closed without merging**
