### PR TITLE
build: update to latest Angular version and TypeScript 4.1

### PR DESCRIPTION
**Pull request by crisbeto**
Updates to the latest versions of Angular and TypeScript.

**Note:** I'm assuming that this is merge safe, because the framework is on TS 4.1 already.

### CODE REVIEW

**Review by jelbourn — APPROVED** [review]
LGTM

**Comment by IgorMinar** [comment]
These tests are failing due to:

```
TypeError: fn.bind is not a function
	    at newTrustedFunctionForJIT (node_modules/@angular/compiler/bundles/compiler.umd.js:7406:19)
	    at JitEvaluator.evaluateCode (node_modules/@angular/compiler/bundles/compiler.umd.js:7464:56)
	    at JitEvaluator.evaluateStatements (node_modules/@angular/compiler/bundles/compiler.umd.js:7438:25)
	    at CompilerFacadeImpl.jitExpression (node_modules/@angular/compiler/bundles/compiler.umd.js:21200:41)
```

Which seems to be coming from https://github.com/angular/angular/blob/b08fd0c18c131917577fc4c952c3d9f42b1e54fa/packages/compiler/src/output/output_jit_trusted_types.ts#L131

And the test fail when executing on Chrome 83.

I wonder if this version of Chrome has an incomplete implementation of trusted types or something. @bjarkler can you please weigh in?

@crisbeto you could also try to update the chrome version to 87.

**Comment by bjarkler** [comment]
This is indeed due to a browser bug. Specifically, calling `eval` with a TrustedScript just returns its value as a string instead of evaluating it as a script, resulting in `fn.bind` being undefined. This bug was introduced in Chrome 83 and fixed in Chrome 84. Upgrading should fix the test failure. (With Chrome 87 already hitting stable, Chrome 83's userbase should have dropped down to a negligible size by now.)

**Comment by crisbeto** [comment]
Thank you for looking into it @IgorMinar @bjarkler. It looks like what was happening is that Browserstack was identifying the Chroimium-based Edge 83 as Chrome 83 which threw me off, because my assumption was that we were always testing against the latest version of Chrome. Bumping it up to 87 resolved the issue. Unblocking the PR now.

**Pull request merged**
