### PR TITLE
fix(material-experimental): errors with latest MDC canary version

### PR DESCRIPTION
**Pull request by crisbeto**
A few hours ago MDC switched all their Sass to use the new Sass modules (see https://github.com/material-components/material-components-web/commit/faa9af310d1a18ec2c183830c84eb14d0492feab). This breaks our MDC components since they've been set up to use global Sass variables. These changes switch all the imports to the `.import` files which use the old approach for exposing variables.

### CODE REVIEW

**Comment by crisbeto** [comment]
Hmm, this was passing locally. Looks like I'll have to spend a bit more time on it. Will ping when Circle is passing as well.

**Comment by crisbeto** [comment]
It should be good to go now. @devversion I don't know whether you want to take one more look at it. I had to switch us to use the Dart version of Sass, because `node-sass` hasn't implemented Sass modules yet.

**Comment by jelbourn** [comment]
Right, I should have given you all a heads up about this (MDC switching to the new Sass module system); we'd been talking about it for a while. The Sass team is working on a project to make dart-sass faster to minimize the perf gap. It looks like `libsass` (on which `node-sass` is based) is now unmaintained and won't be matching Sass features going forward.

**Comment by crisbeto** [comment]
FWIW this shouldn't affect our day-to-day workflow too much since it only applies to the Gulp-based CI tasks.

**Pull request merged**
