### PR TITLE
feat(material/tabs): allow for content tabindex to be customized

### LINKED ISSUE #21819: bug(TABS): Tab panel content not accessible to multiple screen readers
The [WAI-ARIA Example of Tabs with Manual Activation](https://www.w3.org/TR/wai-aria-practices/examples/tabs/tabs-2/tabs.html) puts a tabindex="0" on the tab panel to put it in the page tab sequence to facilitate movement to panel content for assistive technology users. 

Adding tabindex="0" to the mat-tab-body which has the role="tabpanel" attribute would bring the Angular material tabs more in line with the WAI-ARIA authoring practices and "facilitate movement to panel content for assistive technology users".

#### Reproduction

You can see the behavior in the official Stackblitz example: https://stackblitz.com/angular/mgokvrvonpe?file=src/app/tab-group-basic-example.ts

Steps to reproduce:
1. Load Stackblitz example
2. Start a screen reader: JAWS, NVDA or VoiceOver
3. Activate new tab using keyboard
4. Try to navigate to the tab panel so the screen reader can read the content 
 
#### Expected Behavior

A screen reader user should be able to navigate to the tab panel content so it can be read aloud by the screen reader.

#### Actual Behavior

NVDA and VoiceOver are not able to read the tab panel content. 

JAWS provides instructions to use JAWS key + ALT + M to switch to the controlled element, which allows the user to read the tab panel content. But NVDA and VoiceOver don't appear to provide a similar keyboard shortcut.

#### Environment

- Angular: All
- CDK/Material: All
- Browser(s): All
- Operating System (e.g. Windows, macOS, Ubuntu): All

### PR DESCRIPTION
**Pull request by crisbeto**
In some cases, adding a `tabindex` to a `tabpanel` can improve accessibility, however that is currently impossible with our setup, because the element isn't exposed. These changes add an input that allows consumers to customize the `tabindex` based on their use case.

We tried to tackle this in an earlier PR (#14808), but it was decided not to proceed, because the `tabindex` isn't relevant for all use cases. This approach should be a bit more flexible since it allows users to opt into it.

Fixes #21819.

### CODE REVIEW

**Review by jelbourn — COMMENTED** [review]
We should probably also add a style for strong-focus-indicators for a tab body with focus

**Comment by crisbeto** [comment]
Added the strong focus indicator classes to the body.

**Review by jelbourn — APPROVED** [review]
LGTM

**Comment by annieyw** [comment]
This is causing a bunch of screenshot failures where the content gets bunched up and does not take up the whole horizontal space as it should. Any ideas what may be the cause?

**Comment by crisbeto** [comment]
Sorry for the delay @annieyw, I just noticed your comment when coming back to rebase the PR. This sounds weird, because the only style changes are:
1. Adding `outline: 0` to the content. This probably isn't the issue.
2. Adding `mat-focus-indicator` to the content. This may cause some issues, because it adds a `position: relative` and `::after` style.

I've pushed a change to address point 2. Can we re-run the presubmit?

**Pull request merged**
