### PR TITLE
docs(material/checkbox): updated docs for default option value for ch…

### LINKED ISSUE #21025: docs-bug(checkbox): Documentation use "MAT_CHECKBOX_CLICK_ACTION" without notification of deprecation. When MAT_CHECKBOX_DEFAULT_OPTIONS should be used. Errors in v11.
The checkbox documentation page has a section about the usage of "MAT_CHECKBOX_CLICK_ACTION" to define the behavior on clicks. 
It didn't provide any indication that this method is deprecated, nor that it was replaced with  ```{provide: MAT_CHECKBOX_DEFAULT_OPTIONS, useValue: { clickAction: 'noop' } as MatCheckboxDefaultOptions }```

Running a project after upgrading the Angular and Material package will produce an error.

Migration didn't touch this. I don't know if it was updated in earlier migration, since I've only added the provider a week ago, into v10 project. (no notice of deprecation anywhere I saw)

**Affected documentation page:** 
https://material.angular.io/components/checkbox/overview

### PR DESCRIPTION
**Pull request by adhispace**
…eckbox

updates the documentation of customizing the default option of the checkbox.
the default option value to provide for checkbox is MAT_CHECKBOX_DEFAULT_OPTIONS for version>=10

fixes #21025

### CODE REVIEW

**Review by crisbeto — COMMENTED** [review]
Thank you for the PR. The changes look good, but we still have a couple other places where `MAT_CHECKBOX_CLICK_ACTION` is referenced in the docs. Can we take the chance to update them as well?

Here's where it needs to be updated:
```
src\material\checkbox\testing\checkbox-harness.ts
src\material-experimental\mdc-checkbox\testing\checkbox-harness.ts
```

**Comment by adhispace** [comment]
> Thank you for the PR. The changes look good, but we still have a couple other places where `MAT_CHECKBOX_CLICK_ACTION` is referenced in the docs. Can we take the chance to update them as well?
> 
> Here's where it needs to be updated:
> 
> ```
> src\material\checkbox\testing\checkbox-harness.ts
> src\material-experimental\mdc-checkbox\testing\checkbox-harness.ts
> ```

yes. sure...will make changes...

**Comment by adhispace** [comment]
I find `MAT_CHECKBOX_CLICK_ACTION` is also being referenced in 
1) few test case definitions also like
`describe(`when MAT_CHECKBOX_CLICK_ACTION is 'check'`, () => {}`
found in 
src/material-experimental/mdc-checkbox/checkbox.spec.ts
src/material/checkbox.spec.ts
2) src/material/schematics/ng-update/migrations/package-imports-v8/material-symbols.json
line 58 - `  "MAT_CHECKBOX_CLICK_ACTION": "checkbox"`

shall I make changes there as well ? 
thanks

**Comment by crisbeto** [comment]
Let's leave those in since they're unit tests. We can clean them up once the deprecated symbol is removed completely.

**Comment by adhispace** [comment]
> Let's leave those in since they're unit tests. We can clean them up once the deprecated symbol is removed completely.

ok fine...will those..

**Comment by adhispace** [comment]
Hi...I made the suggested changes. but im not sure why the circleci build fails. this is my first PR. if you have time can you please help me solve this. else I shall open a new PR with these changes. 
thanks

**Comment by adhispace** [comment]
I will close this pull request and open a new one :)

**Pull request closed without merging**
