### PR TITLE
build: update to latest versions of bazel setup

### PR DESCRIPTION
**Pull request by devversion**
Updates to the latest versions available for the Bazel setup.
This includes updates of all `@bazel` packages, as well as the
dev-infra private package. This fixes browser testing for Windows x64.

Note: `@bazel/concatjs` is not updated this time as the devserver
implementation is currently broken. We have sent a fix that is being
released as part of `4.2.0` in the near future.

### CODE REVIEW

**Review by crisbeto — APPROVED** [review]
LGTM

**Review by josephperrott — APPROVED** [review]
LGTM

**Comment by wagnermaciel** [comment]
This has merge conflicts with 12.2.x. Can this be `target: minor`?

**Comment by devversion** [comment]
@wagnermaciel yeah

**Pull request merged**
