### PR TITLE
fix(material/sort): programatically setting sort-header active/direction does not update UI

### PR DESCRIPTION
**Pull request by pavelmarozau**
Fixing the issue https://github.com/angular/components/issues/10242

### CODE REVIEW

**Comment by pavelmarozau** [comment]
@googlebot I signed it!

**Comment by crisbeto** [comment]
Would this be covered by https://github.com/angular/components/pull/19492?

**Comment by pavelmarozau** [comment]
> Would this be covered by #19492?

Seems yes, thanks for the reference! :)

**Comment by jelbourn** [comment]
Closing in favor of  #19492. It had some presubmit failures, but I'll have someone take a look and see if we can get it unblocked.

**Pull request closed without merging**
