### PR TITLE
fix(material/snack-bar): update generic types for openFromComponent

### PR DESCRIPTION
**Pull request by GeorgianStan**
Add a generic for MatSnackBarConfig inside openFromComponent method

### CODE REVIEW

**Comment by crisbeto** [comment]
The change looks good, but the CI is failing. You can fix it by:
1. Running `yarn approve-api snack-bar` and committing the changed file.
2. Changing the `material/snackbar` in the commit message title to `material/snack-bar`.

**Comment by crisbeto** [comment]
Technically you can, but it's going to be annoying to get the formatting right.

**Comment by andrewseguin** [comment]
Here's the change you should add to this PR to make CI happy: https://github.com/andrewseguin/components/commit/c8748b035dfff91e064cf0267522aec8837d92a4

**Comment by GeorgianStan** [comment]
@andrewseguin thank you! I updated the PR.

**Comment by andrewseguin** [comment]
Hm seems CI wants you to rebase

**Review by mmalerba — APPROVED** [review]
LGTM

**Pull request merged**
