### PR TITLE
feat(mat/checkbox): add new aria properties to MatCheckbox

### LINKED ISSUE #28761: feat(material/checkbox): MatCheckbox is missing support for aria-expanded attribute
### Feature Description

Based on documentation for [`aria-expanded`](https://developer.mozilla.org/en-US/docs/Web/Accessibility/ARIA/Attributes/aria-expanded#associated_roles) one of the roles with which this attribute is associated with is `role=checkbox`. There is currently no way of providing this `aria-expanded` attribute to the input element generated by MatCheckbox component.

Additionally based on the documentation provided `aria-controls` and `aria-owns` are also missing to indicate to the user which section the output of this input will affect. 

Also see further discussion on [extending support to role=radio](https://github.com/w3c/aria/issues/1404)

### Use Case

Checkbox toggle status expands a related section with further options/information. Screen reader should be able to inform the user of any sections expanded/collapsed as a result of their action

Before
image

After
image

### PR DESCRIPTION
**Pull request by jullierme**
Added three new aria properties to MatCheckbox:

`aria-expanded`: Indicates whether the checkbox controls the visibility of another element. This should be a boolean value (true or false). `aria-controls`: Specifies the ID of the element that the checkbox controls. `aria-owns`: Specifies the ID of the element that the checkbox visually owns. These attributes will be added to the generated checkbox element if they are specified, and won't be present in the HTML if not provided. Also added a small paragraph at the end of the checkbox.md file.

Fixes #28761

### CODE REVIEW

**Review by crisbeto — APPROVED** [review]

**Comment by crisbeto** [comment]
Sorry for the delay here. Can you rebase the PR?

**Comment by jullierme** [comment]
> Sorry for the delay here. Can you rebase the PR?

No problem @crisbeto! It's done now :) There is this  `//tools/public_api_guard:material/checkbox.md_api ` that is failing... Will check it tomorrow

**Comment by crisbeto** [comment]
You just need to run `yarn approve-api checkbox` and push the changed file.

**Comment by jullierme** [comment]
Done, @crisbeto!  Thanks for reviewing it and also the public API info.

**Pull request merged**
