### PR TITLE
build: update to typescript v3.9.5 

### PR DESCRIPTION
**Pull request by devversion**
* Updates to TypeScript v3.9.5
* Updates the size test golden to reflect the latest changes in `master`. This is unrelated to the TS update, but just happened to came to mind when I looked for other size impact due to the update.

### CODE REVIEW

**Comment by mmalerba** [comment]
@devversion needs rebase

**Comment by jelbourn** [comment]
@devversion needs rebase

**Comment by devversion** [comment]
@jelbourn  Rebased

**Comment by jelbourn** [comment]
@devversion changed to `target: minor` due to a merge conflict w/ 10.0.x (since the payload sizes don't exist there)

**Pull request merged**
