### PR TITLE
fix(expansion): add flex-basis to description

### PR DESCRIPTION
**Pull request by william-lohan**
~For https://github.com/angular/material2/issues/10024~
For https://github.com/angular/material2/issues/5173

### CODE REVIEW

**Comment by gatimus** [comment]
I signed it!

**Comment by josephperrott** [comment]
@gatimus Can you push the commit again to have googlebot update the CLA tag.

**Comment by josephperrott** [comment]
It looks like there are CI errors, go ahead and rebase, correct the errors and push again if you can.

**Comment by gatimus** [comment]
@josephperrott done

**Comment by jelbourn** [comment]
@josephperrott is this change still valid?

**Comment by josephperrott** [comment]
Yes, it still should perform the change to the description as expected

**Comment by william-lohan** [comment]
Updated my branch should be merge ready now

**Comment by josephperrott** [comment]
Per https://github.com/angular/components/issues/5173#issuecomment-620764586, closing this issue as this is actually something that should be handled by the client applications rather than the @angular/components library.

**Pull request closed without merging**
