### PR TITLE
Fix/dynamically changing autocomplete

### LINKED ISSUE #13812: Changing the autocomplete on a trigger does not change the overlay (options)
#### Bug, feature request, or proposal:
Changing the autocomplete on a trigger does not change the options in the overlay.

#### What is the expected behavior?
When changing the autocomplete (`dtAutocomplete` input) on a trigger, the overlay should display the new options.

#### What is the current behavior?
When changing the autocomplete (`dtAutocomplete` input) on a trigger, the overlay options
are still the initial ones.

#### What are the steps to reproduce?
https://stackblitz.com/edit/angular-7djgzt?file=app%2Fautocomplete-simple-example.html

#### Which versions of Angular, Material, OS, TypeScript, browsers are affected?
Current

### PR DESCRIPTION
**Pull request by thomaspink**
fixes #13812

This PR is a reopened copy of #13814 because of an accidental merge to master despite breaking some internal google apps.

@mmalerba can you provide the error or some information why this PR did break these apps?

### CODE REVIEW

**Review by crisbeto — DISMISSED** [review]
LGTM. @thomaspink can you rename the PR to the same as the original one?

**Comment by mmalerba** [comment]
@thomaspink I think they had some custom logic to show loading spinners and things. It's probably their app that needs to be updated, not this PR.

**Comment by thomaspink** [comment]
@mmalerba Good to know. thanks for the investigation.

**Comment by thomaspink** [comment]
@crisbeto What do i have to do solve the "commit message fixup"? Squash the commits?

**Comment by vivian-hu** [comment]
Change commit message to `fix(autocomplete): not updating if panel is changed after init`.

**Comment by thomaspink** [comment]
@crisbeto after rebasing the api check fails. There are only minor differences between the golden file and the changed one in the PR.    

`autocomplete.ts`    
* added internal `_portal` property
* added `_viewContainerRef: ViewContainerRef` as a private in constructor
* added `ngAfterViewInit` method    

`autocomplete-trigger.ts`    
* removed `_viewContainerRef: ViewContainerRef` from the constructor

Is there something i have to change/do there?

**Comment by crisbeto** [comment]
You can run `bazel run //tools/public_api_guard:lib_autocomplete_api.accept` to update the golden file.

**Comment by MohammadRafik** [comment]
@thomaspink this PR has fallen out of date, could you please rebase this PR?

**Comment by andrewseguin** [comment]
This PR is being closed due to inactivity and needing rebase for a very long time. Please feel free to re-open the change after rebasing and we can take another look at getting it merged.

**Pull request closed without merging**
