### PR TITLE
Fix: #12803 Alignment of prefixes on inputs with "outline" or "fill" appearance

### PR DESCRIPTION
**Pull request by inorganik**
This is a fix for #12803 - it includes alignment fixes for prefixes on inputs with appearance "fill" or "outline".

### CODE REVIEW

**Comment by inorganik** [comment]
Hey @mmalerba do you have any time to look at this PR?

**Comment by mmalerba** [comment]
It looks good to me, will need to presubmit and see how many screenshot test change inside google because of this though.

**Comment by inorganik** [comment]
Hey @mmalerba looks like we'e almost there. Anything else you'd like me to do to push this over the line?

**Comment by mmalerba** [comment]
The results of the presubmit against google's internal tests show that this causes ~50 screenshot tests to fail. I believe most of the failures are a result of teams that are using CSS overrides to customize the form-field. We'll need to work with those teams to fix the overrides before this can be merged

**Comment by inorganik** [comment]
Thanks, I appreciate the update.

**Comment by inorganik** [comment]
Hey @mmalerba just thought I'd do my weekly checkin. Any movement?

**Comment by ienzam** [comment]
Passing by comment:
Looking at spec, I think
* Prefix/suffix icon and prefix/suffix text needs to be treated differently.
  - Icon should be always visible - .
  - Text should only be visible when label is floating.


## [Prefix icon](https://material.io/design/components/text-fields.html#anatomy)





## [Suffix Icon (Look for "Icons" section in spec)](https://material.io/design/components/text-fields.html)



## [Prefix text (Look for "Prefix and suffix text" section in spec)](https://material.io/design/components/text-fields.html)

**Comment by inorganik** [comment]
Hi @mmalerba just thought I would check and see if there has been any movement. Thanks

**Comment by mmalerba** [comment]
We'll let you know when there's news. It likely won't be merged for a while due to the significant number of projects that need to be fixed first

**Comment by inorganik** [comment]
Hey @mmalerba I keep running into this bug in projects and was hoping there is someway this can be merged. I got my branch caught up. 

@jelbourn I caught your talk and ng-conf about using the CDK. I love the CDK! I recently did a [write-up on integrating CdkDragAndDrop in Material Tree](https://medium.com/briebug-blog/angular-implementing-drag-and-drop-in-a-material-tree-f96b9fe40f81).

**Comment by mmalerba** [comment]
Before we can merge PRs we need to verify that tests written by teams inside google still pass. There is currently a bit of a PR backlog, but we'll do our best to get to it soon

**Comment by andrewseguin** [comment]
Closing since this only affects the legacy form field which will be deprecated in v15 in favor of the MDC version

**Pull request closed without merging**
