### PR TITLE
refactor(multiple): remove coercion members

### PR DESCRIPTION
**Pull request by crisbeto**
* Drops support for TypeScript 4.2. There's a PR that does this already on the Framework side: https://github.com/angular/angular/pull/43281.
* Replaces all usages of the `ngAcceptInputType` members with type declarations directly on the setters.
* Replaces the lint rule that was checking that the correct coercion members were added with a rule that doesn't allow new coercion members to be added.

**Note:** setting this as a P2, because it's prone to merge conflicts.

### CODE REVIEW

**Review by jelbourn — APPROVED** [review]
LGTM

Caretaker note: raise any failures for this for discussion so we can figure out how to resolve them quickly

**Comment by wagnermaciel** [comment]
@crisbeto This has a lot of internal errors because the types of getters and setters don't match.

Here's an example.

```
focus-trap.ts:398:6: ERROR - The types of the getter and setter for property 'enabled' do not match.
getter type is: boolean
setter type is: (boolean|null|string|undefined)
```

**Comment by crisbeto** [comment]
It sounds like g3 is running on TypeScript 4.2 which doesn't support different types for getters and setters. @jelbourn do you know if there's a plan to move to 4.3?

**Comment by jelbourn** [comment]
Yeah, AFAIK that work is actively in progress.

**Review by devversion — APPROVED** [review]

**Comment by crisbeto** [comment]
Closing in favor of https://github.com/angular/components/pull/24055.

**Pull request closed without merging**
