### PR TITLE
refactor(version): Create version subpackages

### PR DESCRIPTION
**Pull request by josephperrott**

### CODE REVIEW

**Comment by josephperrott** [comment]
Caretaker:
This PR will require creating internal BUILD rules and removing the transform created in cl/251715451

**Comment by jelbourn** [comment]
@devversion did we ever add a block for deprecation to the changelog?

**Comment by devversion** [comment]
@jelbourn I think we only created these manually. Did you think about doing this automatically?

**Comment by jelbourn** [comment]
Captured in https://github.com/angular/components/issues/16307

**Pull request closed without merging**
