### PR TITLE
fix(mdc-migration): migrate components selectively bug

### LINKED ISSUE #26426: bug(mdc-migration): Migrate components selectively is bugged
### Is this a regression?

- [ ] Yes, this behavior used to work in the previous version

### The previous version in which this bug was not present was

_No response_

### Description

When Migrating to MDC-based Angular Material Components, and doing it component by component, it should only migrate the selected components. Right now other components that are not selected are also migrated. Seems that it only happens on imports.

Take for example this ngModule code:

```typescript
      import {NgModule} from '@angular/core';
      import {MatLegacyButtonModule} from '@angular/material/legacy-button';
      import {MatLegacyCheckboxModule} from '@angular/material/legacy-checkbox';

      @NgModule({imports: [MatLegacyButtonModule, MatLegacyCheckboxModule]})
      export class AppModule {}
```

Right now, migrating this file selecting only the "button" migrates also the Checkbox. This should not happen. 

### Reproduction

Steps to reproduce:

Execute the migration for only "button" on this ngModule code:

```typescript
      import {NgModule} from '@angular/core';
      import {MatLegacyButtonModule} from '@angular/material/legacy-button';
      import {MatLegacyCheckboxModule} from '@angular/material/legacy-checkbox';

      @NgModule({imports: [MatLegacyButtonModule, MatLegacyCheckboxModule]})
      export class AppModule {}
```

### Expected Behavior

Should migrate only selected components

### Actual Behavior

Selectively migrating components is buggy and in some cases, like imports, other components are also migrated

### Environment

- Angular: 15.1.0
- CDK/Material: 15.1.0
- Browser(s): -
- Operating System (e.g. Windows, macOS, Ubuntu): Ubuntu

### PR DESCRIPTION
**Pull request by llorenspujol**
Fixes mdc-migration to migrate only the selected components.

Fixes #26426

### CODE REVIEW

**Review by amysorto — APPROVED** [review]

**Comment by mmalerba** [comment]
@llorenspujol It looks like this change caused it to stop migrating `legacy-core` when using `--components all`. I've added a commit with the changes to the golden test so you can see what changed (easier to look at the github diff than the test output). In order to merge we'll need to fix. You can run `yarn bazel run //integration/mdc-migration:test.approve` to re-approve the golden test changes after making changes. Once fixed properly, it should just negate the changes in the commit I added.

**Comment by llorenspujol** [comment]
> @llorenspujol It looks like this change caused it to stop migrating `legacy-core` when using `--components all`. I've added a commit with the changes to the golden test so you can see what changed (easier to look at the github diff than the test output). In order to merge we'll need to fix. You can run `yarn bazel run //integration/mdc-migration:test.approve` to re-approve the golden test changes after making changes. Once fixed properly, it should just negate the changes in the commit I added.

Yes, I see, thanks for the commit. What is happening here is that `MatLegacyOptionModule` comes from 'legacy-core', not 'legacy-option', so it fails.
I just went straightforward, and to solve it, I always replace imports that come from 'legacy-core'. This solution is not 100% perfect, since if one user is not migrating any component related to `MatOptionModule`, it will either way migrate it. I think it is an edge case thought, since it may be very strange using the `MatOptionModule` alone, but it can happen.

The perfect solution may be one that resolves this test:

```typescript
it('should not replace only mat legacy option module if not specified', async () => {
    await runMigrationTest(
      `
        import {NgModule} from '@angular/core';
        import {MatLegacyOptionModule, LEGACY_VERSION} from '@angular/material/legacy-core';
        @NgModule({imports: [MatLegacyOptionModule]})
        export class AppModule {}
      `,
      `
        import {NgModule} from '@angular/core';
        import {MatLegacyOptionModule} from '@angular/material/legacy-core';
        import {VERSION} from '@angular/material/core';
        @NgModule({imports: [MatOptionModule]})
        export class AppModule {}
      `,
    );
  });
```
IMO I think is really an edge case, and we can go with it as it is. That being said, if this test needs to be solved for X reasons, we can do it, I just want to first validate the task before putting any more effort on it!

**Comment by michaelfaith** [comment]
One thought, is you could have a separate const array that consists of the `options.components` that are exported from `legacy-core` (it may just be `option` in this case) and change the first condition to check if 
```typescript
(lastImportName  === 'legacy-core'  && CORE_COMPONENTS.some((coreComponent) => lastImportName.includes(coreComponent)))
```

**Comment by mmalerba** [comment]
I think it should be fine to only migrate core symbols when `option` or `optgroup` is chosen for migration. A check like the one @michaelfaith suggested should work for that

**Comment by llorenspujol** [comment]
Agreed, it makes more sense this way. I added the necessary changes to only migrate core symbols if `option` or `optgroup` is chosen for migration. The code is basically as @michaelfaith pointed out 👌

**Comment by michaelfaith** [comment]
I think all of the feedback items have been addressed on this.  Or is there more to do?

**Review by mmalerba — APPROVED** [review]
LGTM

**Pull request merged**
