### PR TITLE
fix(material/input): don't remove the placeholder attribute

### PR DESCRIPTION
**Pull request by mmalerba**
It was only removed to support the legacy form-field, and removing it
creates problems for other directives that may need to read it (e.g.
textarea autosize).

### CODE REVIEW

**Comment by crisbeto** [comment]
It isn't really there to support the `legacy` appearance though, it's so that screen readers don't read out the same placeholder twice. I'm not sure that we can remove it without removing the `legacy` appearance. We could try to limit it further, but the `_hideControlPlaceholder` which it's based upon is already very narrow.

**Comment by mmalerba** [comment]
Does this ever happen on form-fields that don't have the legacy appearance?

My understanding is that its purely for the sake of not reading the placeholder twice on the legacy form-field. If that's the case and we're ok with autosize possibly making the textarea smaller than the placeholder in the legacy form-field I can just close this. I've already updated #22314 to just test a different appearance

**Comment by crisbeto** [comment]
It's only relevant in `legacy`, but I think that we'll have to keep it because it is still the default `appearance` for `mat-form-field`. Maybe in #22314 we could detect if the `textarea` is a `MatInput` and have it look at `data-placeholder` as well?

**Comment by mmalerba** [comment]
I don't want to add any more cruft to support the legacy style. I'd rather just only support the placeholder in autosize for the newer appearances. I'll close this and just go ahead with the other PR without legacy support

**Pull request closed without merging**
