### PR TITLE
fix(cdk/drag-and-drop): cdkDrag directive override transform styles

### LINKED ISSUE #18143: cdkDrag override transform styles
#### Bug, feature request, or proposal:
Bug

#### What is the expected behavior?
When I have transform style on my draggable element, after dragging the transform style will remain.

#### What is the current behavior?
When I have transform style on my draggable element, after start dragging the transform style is overridden.

#### What are the steps to reproduce?
For example add `transform: rotate(45deg);` to `.example-box` here:
https://stackblitz.com/angular/lkdvnnkjmlq?file=src%2Fapp%2Fcdk-drag-drop-overview-example.css
You can notice that after dragging the rotate will disappear.
But, if you will add the `transform: rotate(45deg);` in `style` attribute you will see that the expected behavior is achieved.

#### Which versions of Angular, Material, OS, TypeScript, browsers are affected?
@angular/cdk/drag-drop 8.2.3

### PR DESCRIPTION
**Pull request by Sagie501**
Fixes the bug that cdkDrag directive override transform styles on the root element

Fixes #18143

### CODE REVIEW

**Comment by Sagie501** [comment]
@googlebot I signed it!

**Comment by clabough** [comment]
What's the status of this? I want to be able to rotate the drag preview, but the root element transform gets overwritten if I use CSS and using a custom preview, the closest I could get was this.

https://stackblitz.com/edit/angular-odwl6v?file=src%2Fapp%2Fcdk-drag-drop-connected-sorting-group-example.html

**Comment by Gamelena** [comment]
This fix was accepted? if yes in which version is dispossable? I had the same issue using @angular/cdk@7.3.7

**Comment by devversion** [comment]
Hey, please re-open the pull request if still valid. The PR got auto-closed by GitHub when we renamed our primary branch.

**Pull request closed without merging**
