### PR TITLE
Fix accessibility table examples

### PR DESCRIPTION
**Pull request by forsti0506**
Hello,

I'd like to commit some fixes to the accessibility of the angular examples. In my opinion many people are copying these examples and therefore it is important to provide accessible examples.

First I added an arrow to expand tables, because otherwise the row is only accessible by clicking with a mouse!

I hope you have time to review my first Pull request!

The `nbsp; is needed, because for example NVDA doesn't recognize it, if it is used without any content!

Second Part is to enable focusing scrollable regions to ensure that screen an tabusers can access them!

Thanks in Advance!

Best regards,

Martin

### CODE REVIEW

**Review by andrewseguin — COMMENTED** [review]
Thanks for the contribution. Just one thing to change and we can get these changes in.

**Comment by forsti0506** [comment]
@andrewseguin  Maybe I missed the suggested change, but I can't see the thing to change?

**Comment by andrewseguin** [comment]
Odd my comment didn't get through, maybe because it's not an affected line. Be sure to change `[attr.colspan]="columnsToDisplay.length"` to use `columnsToDisplayWithExpand` instead so that the bottom border stretches across all cells

**Comment by forsti0506** [comment]
I added the fix.

Maybe one question from me: I saw there is an experimental section too for table. Should I apply the fix there too in this PR?

**Comment by andrewseguin** [comment]
Yes - that'd be great if you can add the fix to the MDC based versions. We're working on making those the primary versions now

**Comment by forsti0506** [comment]
@andrewseguin I added the features for the mdc examples.

I'm not sure how to fix the CircleCi errors, because the build fails because of my master merge!

**Comment by andrewseguin** [comment]
It looks like one of the issues is that `table-sticky-complex-flex-example.html` has the beginning `div` switched to a `section` but not the closing `div`

**Comment by forsti0506** [comment]
Yes thanks: closing tag is fixed, but I think the merge is blocked, because of the commit message for the master merge!

**Review by andrewseguin — APPROVED** [review]

**Pull request merged**
