### PR TITLE
style(input): increase line-height for input

### LINKED ISSUE #9738: mat-hint type descender and uppercase accents are cropped in mat-form-field
#### Bug, feature request, or proposal:

Bug

#### What is the expected behavior?

All alphabet letters should be readable.

#### What is the current behavior?

The lower case letters that have descenders  (`g`, `j`, `p`, `q` and `y`) should not be cropped in `mat-hint`

#### What are the steps to reproduce?

* Go to https://material.angular.io/components/input/overview#changing-when-error-messages-are-shown
* Take a look at the example, the `y` from the "Errors appear instantly!" hint is cropped at the button, this would be more obvious if you open your dev-tools and add a `g` in there (the curved descender goes away)
  image

#### What is the use-case or motivation for changing an existing behavior?

Text readability.

#### Which versions of Angular, Material, OS, TypeScript, browsers are affected?

Probably a very recent build, the package-lock.json from the material.angular.io repo points to a commit.

#### Is there anything else we should know?

1. I've tested only on openSUSE Linux.

2. The Material Design specification doesn't say much about the "Helper text": https://material.io/guidelines/components/text-fields.html#text-fields-layout

3. The `.mat-form-field` line-height is inherited by `.mat-hint`. The problem goes away if you add `.mat-hint { line-height: initial; }`, but this solution doesn't seem right, probably, the line-height on the .mat-form-field should not be that small: 1.125

### PR DESCRIPTION
**Pull request by SchnWalter**
Fix cropping issue for mat-input fields, previous line-height was to small for the used font.

Closes #9738

### CODE REVIEW

**Comment by SchnWalter** [comment]
@mmalerba, I've created this PR so that we can discuss here on what is the best approach to fix the issue. I haven't checked the code yet. But will need to make sure that the layout for the various version of the input field don't break.

**Comment by mmalerba** [comment]
Yeah I think this might be a little trickier if we want to do it and keep the spacing as close to the spec as possible (the spec annoyingly doesn't account for line-height). Even now I don't think the spacing is quite what is supposed to be at 16px font-size, which is what the spec shows.

One thing I was thinking about trying is setting `margin-top` and `margin-bottom` on the label, input, hint, etc to `-0.25em`. I want to take some time to experiment with it and use this as an opportunity to try to get a little closer to the spec.

Feel free to do your own experimentation and let me know if you find something that works well. Things to make sure you consider / test:
- The standard, box, and fill appearances (I don't care so much about legacy because we want people to move off of it after 6.0.0) and making sure that the underlines for each line up in a centered flex box
- The baseline alignment of the `<input>` text with text outside of the form-field
- Form fields with label, placeholder, hints, errors
- Alignment of popup boxes like datepicker and autocomplete
- Different form-field control elements (input, textarea, mat-select, chip-list)
- Center alignment of icon, icon-button, datepicker toggle, and select arrow

**Comment by mmalerba** [comment]
Oh great, thanks for the research! I must admit, I had never noticed that part of the spec before. Having `is-tall` and `is-dense` is an interesting idea, but as you say its a pretty large undertaking. I think we should file a feature request to hopefully add something like that down the line. In the mean time I think we can fix the `line-height` to work with english-like languages for the three new `mat-form-field` variations before 6.0.0 goes out, that way it won't be a drastic change for people, they'll just get the fix at their own pace as they move their `appearance="legacy"` `mat-form-field`s to `appearance="standard"`.

**Comment by SchnWalter** [comment]
I've done some digging around in order to determine what would be the optimal line-height for the Roboto font.

Here's a generated report using `source-foundry/font-line`, it includes fonts for all languages (including dense&tall) and has the `(Typo Asc + Desc + Linegap) / UPM` ratio is 1.32, so I believe that for tall languages we can use this value for the line-height, if that is the +0.1em, that would leave us with `1.20` line-height for English-like languages... which I've tested and it work OK-ish, except for the descenders in openSUSE, which require a line height of exactly `1.25`... but this could be an openSUSE issue.

```
$ font-line report ./Roboto-Regular.ttf

=== ./Roboto-Regular.ttf ===
Version 2.001047; 2015
SHA1: 06691e103d4d3ce1f1108d9b7d21254b714a41f8

--- Metrics ---
[head] Units per Em:    2048
[head] yMax:            2163
[head] yMin:            -555
[OS/2] CapHeight:       1456
[OS/2] xHeight:         1082
[OS/2] TypoAscender:    2146
[OS/2] TypoDescender:   -555
[OS/2] WinAscent:       2146
[OS/2] WinDescent:      555
[hhea] Ascent:          2146
[hhea] Descent:         -555

[hhea] LineGap:         0
[OS/2] TypoLineGap:     0

--- Height Calculations by Table Values ---
[OS/2] TypoAscender to TypoDescender:   2701
[OS/2] WinAscent to WinDescent:         2701
[hhea] Ascent to Descent:               2701

--- Delta Values ---
WinAscent to TypoAscender:      0
Ascent to TypoAscender:         0
WinDescent to TypoDescender:    0
Descent to TypoDescender:       0

--- Ratios ---
(Typo Asc + Desc + Linegap) / UPM:      1.32
(winAsc + winDesc) / UPM:               1.32
(hhea Asc + Desc) / UPM:                1.32
```

And I've also extracted these individual values, manually, and `1.20` seems to be the way to move forward.

| Name | Char | Y-min | Y-max | Notes |
|------|------|------|------|-------|
| LATIN CAPITAL LETTER X | X | 0 | 1456 | "CapHeight" |
| LATIN SMALL LETTER X | x | 0 | 1082 | "xHeight" |
| - | - | - | - | - |
| LATIN CAPITAL LETTER A WITH ACUTE | Á | 0 | 1846 |
| LATIN CAPITAL LETTER A WITH BREVE | Ă | 0 | 1806 |
| LATIN CAPITAL LETTER A WITH CIRCUMFLEX | Â | 0 | 1846 |
| LATIN CAPITAL LETTER A WITH OGONEK | Ą | -433 | 1456 |
| LATIN CAPITAL LETTER A WITH RING ABOVE | Å | 0 | 1937 | tallest, part of the Sweedish alphabet |
| LATIN CAPITAL LETTER C WITH ACUTE | Ć | -20 | 1879 |
| LATIN CAPITAL LETTER E WITH ACUTE | É | 0 | 1858 |
| LATIN CAPITAL LETTER I WITH CIRCUMFLEX | Î | 0 | 1858 |
| LATIN CAPITAL LETTER N WITH CEDILLA | Ņ | 0 | 1456 |
| LATIN CAPITAL LETTER N WITH TILDE | Ñ | 0 | 1826 |
| LATIN CAPITAL LETTER T WITH COMMA BELOW | Ț | -511 | 1165 |
| LATIN SMALL LETTER C WITH CEDILLA | ç | -444 | 1102 |
| LATIN SMALL LETTER G | g | -426 | 1102 |
| LATIN SMALL LETTER J | j | -437 | 1476 |
| LATIN SMALL LETTER P | p | -416 | 1102 |
| LATIN SMALL LETTER Q | q | -416 | 1102 |
| LATIN SMALL LETTER T WITH COMMA BELOW | ț | -513 | 1344 | lowest, part of Romanian alphabet |

**Comment by SchnWalter** [comment]
Hm... I've tested a fresh version of the font from fonts.gstatic.com, the previous one was from the Debian 9 (stretch) repo:
```
$ font-line report Roboto-Regular-fonts.gstatic.com.ttf

=== Roboto-Regular-fonts.gstatic.com.ttf ===
Version 2.137; 2017
SHA1: a867d820f494f954122e8ca663d943690256f9f4

--- Metrics ---
[head] Units per Em:    2048
[head] yMax:            2163
[head] yMin:            -555
[OS/2] CapHeight:       1456
[OS/2] xHeight:         1082
[OS/2] TypoAscender:    1536
[OS/2] TypoDescender:   -512
[OS/2] WinAscent:       1946
[OS/2] WinDescent:      512
[hhea] Ascent:          1900
[hhea] Descent:         -500

[hhea] LineGap:         0
[OS/2] TypoLineGap:     102

--- Height Calculations by Table Values ---
[OS/2] TypoAscender to TypoDescender:   2048
[OS/2] WinAscent to WinDescent:         2458
[hhea] Ascent to Descent:               2400

--- Delta Values ---
WinAscent to TypoAscender:      410
Ascent to TypoAscender:         364
WinDescent to TypoDescender:    0
Descent to TypoDescender:       -12

--- Ratios ---
(Typo Asc + Desc + Linegap) / UPM:      1.05
(winAsc + winDesc) / UPM:               1.2
(hhea Asc + Desc) / UPM:                1.17
```


And then I went ahead and tested the openSUSE font which was also installed from the repository:

```
$ font-line report Roboto-Regular.opensuse.ttf

=== Roboto-Regular.opensuse.ttf ===
Version 2.001047; 2015
SHA1: 06691e103d4d3ce1f1108d9b7d21254b714a41f8

--- Metrics ---
[head] Units per Em:    2048
[head] yMax:            2163
[head] yMin:            -555
[OS/2] CapHeight:       1456
[OS/2] xHeight:         1082
[OS/2] TypoAscender:    2146
[OS/2] TypoDescender:   -555
[OS/2] WinAscent:       2146
[OS/2] WinDescent:      555
[hhea] Ascent:          2146
[hhea] Descent:         -555

[hhea] LineGap:         0
[OS/2] TypoLineGap:     0

--- Height Calculations by Table Values ---
[OS/2] TypoAscender to TypoDescender:   2701
[OS/2] WinAscent to WinDescent:         2701
[hhea] Ascent to Descent:               2701

--- Delta Values ---
WinAscent to TypoAscender:      0
Ascent to TypoAscender:         0
WinDescent to TypoDescender:    0
Descent to TypoDescender:       0

--- Ratios ---
(Typo Asc + Desc + Linegap) / UPM:      1.32
(winAsc + winDesc) / UPM:               1.32
(hhea Asc + Desc) / UPM:                1.32
```

Judging by the looks of this... we should not hurry up and make changes. In both cases (Debian & openSUSE) the font was provided by the OS and it was an older version. I'm not sure how or if this problem should be addressed. Maybe we should check tha `overflow: hidden` after all, an just keep things as they are.

**Comment by mmalerba** [comment]
Ah interesting, I wonder if there's any way to require a min version of some font. The `overflow: hidden` is there to prevent the error message from displaying on top of the input as it animates in. If we can find some other way of fixing the animation we can remove it.

**Comment by mmalerba** [comment]
It looks like when you load the font via the Google Fonts API it first looks for local versions: https://fonts.googleapis.com/css?family=Roboto

One workaround would be to write these `@font-face` declarations manually and leave off the `local(...)` part. It would mean that people who have the correct version would still have to download it though. If you really want to get fancy you could programmatically generate different `@font-face` declarations based on the OS you detect. [Web Font Loader](https://github.com/typekit/webfontloader) would probably be useful for that.

**Comment by mmalerba** [comment]
I believe the cropping issue has been resolved. It was caused by an old version of the Roboto font that shipped with Debian. That has since been updated

**Pull request closed without merging**
