### PR TITLE
refactor: make all event emitters readonly

### PR DESCRIPTION
**Pull request by rafaelss95**
Basically the same idea of PR #9586, which _fixed_ #9582, but unfortunately didn't add a TSLint rule to keep these changes consistent.

Now, I'm adding `Codelyzer`'s `prefer-output-readonly` rule to the `tslint.json` :).

### CODE REVIEW

**Comment by rafaelss95** [comment]
> This feels redundant IMO. It makes us write more code while enforcing a rule that hasn't been an issue until now.

Hmm... I thought it was an issue since #9582 was created explicitly to do this. The problem is that in the PR abovementioned I didn't add a rule to keep it consistent. That said, should I close this then?

**Comment by crisbeto** [comment]
I think that @jelbourn can say whether that issue is still relevant since it's very old.

**Comment by jelbourn** [comment]
I do think we should still do this. It may be a bit of extra effort, but it is more correct.

**Review by mmalerba — APPROVED** [review]
LGTM

**Comment by rafaelss95** [comment]
@mmalerba, could you please suggest a commit message to make lint happy? :)

**Comment by crisbeto** [comment]
You have to add a scope to it, e.g. `refactor(<scope>): make all event emitters readonly`. These are the possible scopes: https://github.com/angular/components/blob/master/.ng-dev/commit-message.ts#L10

**Comment by rafaelss95** [comment]
@crisbeto Thanks for the link! I looked at it and I couldn't find a suitable one, as the changes are being applied to several places at the same time.

**Comment by mmalerba** [comment]
Yeah our commit message format doesn't work well for changes like this. You can just pick one, material/core maybe

**Comment by annieyw** [comment]
@rafaelss95 please rebase/fixup message when you get the chance

**Comment by rafaelss95** [comment]
@mmalerba @annieyw sorry for the delay, I rebased and fixed up the commit message.

**Pull request merged**
