### PR TITLE
fix(material-experimental/mdc-tooltip): change class prefixes to mat-mdc

### PR DESCRIPTION
**Pull request by mmalerba**

### CODE REVIEW

**Review by annieyw — APPROVED** [review]
lgtm, I think you also need to fix the spelling in the mdc-tooltip test (failing lint check)

**Comment by wagnermaciel** [comment]
@mmalerba Won't we also need to update the docs for this, since we're changing `TOOLTIP_PANEL_CLASS`?
https://material.angular.io/components/tooltip/api#TOOLTIP_PANEL_CLASS

**Review by crisbeto — APPROVED** [review]
LGTM

**Comment by mmalerba** [comment]
@wagnermaciel updated to not change that constant and just deprecate it for later removal

**Pull request merged**
