### PR TITLE
docs(material/dialog): fix typo in animation description

### PR DESCRIPTION
**Pull request by oleksiipotiekhin**
Fixes a typo in the description of dialog container animations file.

### CODE REVIEW

**Comment by crisbeto** [comment]
The change looks good, but the commit message needs to be changed to something like `docs(material/dialog): fix typo in animation description` in order to pass the formatting check.

**Comment by oleksiipotiekhin** [comment]
> The change looks good, but the commit message needs to be changed to something like `docs(material/dialog): fix typo in animation description` in order to pass the formatting check.

Done.

**Comment by crisbeto** [comment]
Your change only renamed the pull request. In order for the lint check to pass, the commit message itself needs to be changed.

**Review by crisbeto — APPROVED** [review]

**Comment by oleksiipotiekhin** [comment]
@jelbourn

**Pull request merged**
