### PR TITLE
docs: use material button for cdk example

### PR DESCRIPTION
**Pull request by santoshyadav198613**

### CODE REVIEW

**Comment by jelbourn** [comment]
We do intentionally use non-Material controls for CDK examples to reinforce the idea that the CDK is not coupled to Angular Material

**Comment by santoshyadav198613** [comment]
> We do intentionally use non-Material controls for CDK examples to reinforce the idea that the CDK is not coupled to Angular Material

Ohh that's great, but I can see failing test case, it says it will not work with mat-button, is that the case?

**Comment by devversion** [comment]
@santoshyadav198613 Can you please be more concrete what is failing for you? i.e. a concrete example, link to the docs?

**Comment by santoshyadav198613** [comment]
> @santoshyadav198613 Can you please be more concrete what is failing for you? i.e. a concrete example path or a link to the docs? thanks!

I am referring to 
src/components-examples/cdk/a11y/focus-monitor-focus-via/focus-monitor-focus-via-example.html:16:58 - error TS2769: No overload matches this call.
  Overload 1 of 2, '(element: HTMLElement, origin: FocusOrigin, options?: FocusOptions | undefined): void', gave the following error.
    Argument of type 'MatButton' is not assignable to parameter of type 'HTMLElement'.
      Type 'MatButton' is missing the following properties from type 'HTMLElement': accessKey, accessKeyLabel, autocapitalize, dir, and 232 more.
  Overload 2 of 2, '(element: ElementRef<HTMLElement>, origin: FocusOrigin, options?: FocusOptions | undefined): void', gave the following error.
    Argument of type 'MatButton' is not assignable to parameter of type 'ElementRef<HTMLElement>'.
      Property 'nativeElement' is missing in type 'MatButton' but required in type 'ElementRef<HTMLElement>'.

**Comment by devversion** [comment]
I see, but that failure only happens in this PR because you added `MatButton` to a CDK example. It's certainly possible to use `MatButton` in this example, but then other adjustments would need to be made, as currently the `FocusMonitor` accepts native elements, and not an instance of `MatButton`.

Generally, I think we don't want to add `MatButton` to these examples, as they are decoupled from Angular Material (there seem to be exceptions; but that's the actual idea)

**Pull request closed without merging**
