### PR TITLE
refactor: fix typescript 3.7 compilation errors.

### PR DESCRIPTION
**Pull request by andrius-pra**
Fixes `Import declaration conflicts with local declaration` error.

### CODE REVIEW

**Comment by jelbourn** [comment]
Caretaker: cherrypick this into the 9.0.x branch

**Comment by devversion** [comment]
Actually, the `FloatLabelType` should not be deleted, and the import should be removed.

**Comment by devversion** [comment]
Thanks for updating @andrius-pra. Looks like this unveiled another issue. Can you update src/dev-app/mdc-input/mdc-input-demo.ts#L11 to not import `FloatLabelType` from core, but from the `mdc-form-field` import? I think/hope that this should make CI green.

**Comment by andrius-pra** [comment]
Done

**Comment by devversion** [comment]
Marking as P2 to unblock the TypeScript 3.7 update PR on framework.

**Pull request merged**
