### PR TITLE
 cdkConnectedOverlay should let us change positioning strategy

### PR DESCRIPTION
**Pull request by mertdeg2**
The problem is that this directive is not flexible enough to pass in arbitrary positioning strategy.

### CODE REVIEW

**Comment by crisbeto** [comment]
Doesn't this somewhat defeat the purpose of the directive? If you're already creating the strategy, the rest of the overlay only needs a few more lines of code.

**Comment by mertdeg2** [comment]
We have an internal component that is built on top of this directive. 

We use all of the other features. But the positioning strategy is not overridable. It mostly looks like below:

```
<ng-template
  cdkConnectedOverlay
  [cdkConnectedOverlayHasBackdrop]="hasBackdrop"
  [cdkConnectedOverlayBackdropClass]="getBackdropClasses()"
  [cdkConnectedOverlayOrigin]="trigger"
  [cdkConnectedOverlayPositionStrategy]="positionStrategy"
  [cdkConnectedOverlayOpen]="isOpen"
  [cdkConnectedOverlayPositions]="positions"
  [cdkConnectedOverlayMinWidth]="minWidth"
  [cdkConnectedOverlayViewportMargin]="overlayViewportMargin"
  [cdkConnectedOverlayGrowAfterOpen]="true"
  [cdkConnectedOverlayPush]="true"
  (backdropClick)="close()"
  (detach)="close()">
```

**Comment by crisbeto** [comment]
Leaving up to @jelbourn on how to proceed here, but it'll definitely need some unit tests.

**Comment by mertdeg2** [comment]
Added a unit test for this.

**Comment by jelbourn** [comment]
@mertdeg2 overall looks good but there are some failures on CI

**Comment by mertdeg2** [comment]
I think i fixed the failures on CI

**Pull request merged**
