### PR TITLE
feat(range-slider): Add range-slider (double-slider) functionality slider component

### PR DESCRIPTION
**Pull request by PhilippS93**
- Added range slider "two thumb" like shown in the material [spec](https://material.io/design/components/sliders.html#usage)

- Added demo in the material demo-app.

sliders

See: [#1331](https://github.com/angular/material2/issues/1331)

### CODE REVIEW

**Comment by Journeycorner** [comment]
Any news on when this is going to land? Otherwise I need to hack a solution for ssr.

**Comment by MaximilianGraef** [comment]
Iam looking forward to this for ages. Please let it happen :)

**Comment by jelbourn** [comment]
Hey there- we really appreciate the enthusiasm for this feature. For the time being, we aren't going to add this to the mat-slider. While we know a many people want this feature, this is countered by:
* Range sliders aren't captured in the Material Design spec; we don't want to open up an interaction pattern to Google applications that the Material Design UX team doesn't approve of.
* We're working on a way to share some code with the Material Design team (MDC web), and they also don't support range sliders.
* Any implementation would have to have a solid a11y interaction pattern for screen-reader users. This would require a bit more work, since it would mean that a range slider would likely have to present itself as multiple `role="range"` elements. 

We definitely encourage you to share your work as a standalone component, though!

**Comment by Journeycorner** [comment]
There is a range slider shown on the official material page, looks like
there is indeed a spec!

Jeremy Elbourn <notifications@github.com> schrieb am Fr., 26. Okt. 2018,
19:17:

**Comment by Journeycorner** [comment]
@jelbourm There is a range slider shown on the official material page, how can it be not in the spec? https://material.io/design/components/sliders.html#

**Comment by jelbourn** [comment]
Huh, I hadn't noticed that one image before. It's strange that exists there but isn't mentioned anywhere else on the page. I'll check with the Material Design UX team to see if it's intentional.

**Comment by jelbourn** [comment]
Following up: talking to someone from the Material Design team, they say that that one image in the spec really shouldn't be in there since the range slider isn't otherwise specified. There's an open bug now to remove it.

**Comment by odahcam** [comment]
Material Design spec always had range slider images but no text about it and no design alternatives for it. It would be nice to give us some alternative to range sliders if they aren't a good UI component. @jelbourn are currently there any components in this lib we can use as an alternative to range sliders?

**Comment by drenda** [comment]
Hi guys, any news about this new function?

**Comment by djtahl** [comment]
Hello guys, is there a way to access this "open bug" in Material Design project and have more visibility on wether there is a possibility to add the specs someday for such iteration on the slider component ?
We also need this type of slider with double inputs.

**Comment by AndreasDeNeve** [comment]
Any timeline available for resolving the merge conflicts + PR review?

**Comment by manuelarte** [comment]
really looking forward to this feature

**Comment by odahcam** [comment]
Anyone knows something about a standalone component compatible with Angular Material?

**Comment by Vlad-Fernandes** [comment]
Any updates on when this new function will be merged and added to the slider

**Comment by preda7or** [comment]
Now that Flutter has double thumb slider too. Could we revive this PR?

**Comment by mmalerba** [comment]
The MDC team does plan to build a slider with multiple thumbs, and we plan to build one based on that once its done

**Comment by mohitvirli** [comment]
Any updates on this PR (looks stale) or is there another one tracking this? Thanks.

**Comment by jelbourn** [comment]
Closing this since we don't plan on adding range functionality to the _current_ MatSlider. We will be making a new slider based on top of MDC Web's slider, which does already support range.

**Comment by odahcam** [comment]
Is there a ETA or roadmap for the new slider?

**Comment by jelbourn** [comment]
No ETA, but the MDC versions of the components are the team's main priority

**Pull request closed without merging**
