### PR TITLE
fix(google-maps): correct minor typo in the code

### PR DESCRIPTION
**Pull request by ilmalte**
Position's comment is wrong

### CODE REVIEW

**Comment by ilmalte** [comment]
@googlebot I signed it!

**Review by crisbeto — COMMENTED** [review]
The change looks good, but the CI won't pass because the commit message title isn't formatted correctly. It should start with `fix(google-maps)`.

**Comment by ilmalte** [comment]
Thank you for your review @crisbeto !
It's my first pull request. I have just followed your suggestions but it looks like CI still don't pass my commit. Can you help me?

**Comment by crisbeto** [comment]
It's because you only renamed the pull request, but the commit still has its old name. See:

fix(google-maps)_correct_minor_typo_in_the_code_b_2021-02-12_21-54-50

**Review by ilmalte — COMMENTED** [review]
Does I need to pull another request with the right commit name or is it a thing you can rename for me?

**Comment by crisbeto** [comment]
You'll have to rename it yourself. It doesn't have to be in a new PR. Here's some info on how to rename a commit https://docs.github.com/en/github/committing-changes-to-your-project/changing-a-commit-message

**Pull request closed without merging**
