### PR TITLE
feat(material/schematics): add fn for adding attrs to templates

### PR DESCRIPTION
**Pull request by wagnermaciel**
* create and unit test addAttribute fn

### CODE REVIEW

**Review by devversion — APPROVED** [review]
LGTM, a test scnario for multiple arguments on a single element would be cool.

**Comment by wagnermaciel** [comment]
> LGTM, a test scnario for multiple arguments on a single element would be cool.

@devversion That's outside of the scope of what's needed for the migration. We'll only need to add a single one. Would be easy to add that functionality in if it becomes relevant in the future

**Comment by devversion** [comment]
> @devversion That's outside of the scope of what's needed for the migration. We'll only need to add a single one. Would be easy to add that functionality in if it becomes relevant in the future

My philosophy usually is: if you are building a generic utility like this, and this is a common scenario usually, then it should be tested as it's low-effort (4-5 lines), proofs that the API can be useful for other usages as well, and _works_ (because future uses might not be testing all code paths -- its easy to forget about this then 😛 )

**Comment by wagnermaciel** [comment]
@devversion I think I may have misunderstood you. Did you want to test using the `addAttribute` fn multiple times or extend and then test the functionality of addAttribute so that it could add multiple attributes like this
```
addAttribute(html: string, node: Element, attributes: {[key: string]: string}[])
```

**Comment by devversion** [comment]
@wagnermaciel I was just thinking of having a test where you'd call `addAttribute` multiple times. Sorry if that was unclear.

**Comment by wagnermaciel** [comment]
@devversion Ah, gotcha. No problem then, I'll just throw in a test for it in a follow-up PR 👍🏽

**Pull request merged**
