### PR TITLE
fix(paginator): button labels being read out twice by assistive technology

### PR DESCRIPTION
**Pull request by crisbeto**
Currently the paginator has an `aria-label` and a tooltip with the same text which sets an `aria-describedby`. The result is that screen readers read out the same text twice which is  unnecessary. These changes remove the `aria-label`, leaving only the ARIA descriptions from the tooltips.

### CODE REVIEW

**Comment by jelbourn** [comment]
This isn't really the best approach. The buttons should keep their `aria-label` and lose the duplicate `aria-describedby`.

**Comment by crisbeto** [comment]
The result seems to be the same though: the screen reader just reads out something like "Next page" when you focus the input in both cases.

**Comment by jelbourn** [comment]
At least for audit tools like axe, though, the assertion is that every button has a "label", which `aria-describedby` does not satisfy. I don;' know without testing, but I _suspect_ some screen-readers might also treat them differently.

**Comment by crisbeto** [comment]
This change shouldn't be necessary anymore after the fix in #15250.

**Pull request closed without merging**
