### PR TITLE
refactor(multiple): enable `noImplicitOverride` typescript option

### PR DESCRIPTION
**Pull request by devversion**
Enables the TypeScript `noImplicitOverride` option and adds
the `override` keyword where needed.

### CODE REVIEW

**Comment by devversion** [comment]
Blocked on Google3 updating to TS 4.3

**Review by mmalerba — APPROVED** [review]
ooh nice, didn't know this was a thing

**Review by andrewseguin — APPROVED** [review]
Huh thats neat - thanks for making this change

**Review by josephperrott — APPROVED** [review]
LGTM

**Pull request merged**
