### PR TITLE
refactor(multiple): replace hasError() with errors

### PR DESCRIPTION
**Pull request by ice-blaze**
Angular documentation use errors instead of hasError. Since the function is called in the template and it's not recommended to call functions within a template, we replaced it with errors.

related issue #28883

### CODE REVIEW

**Comment by crisbeto** [comment]
I asked around about this in our internal chat. Both `errors` and `hasError` are supported APIs. I think I'd lean more on `hasError`, because it's a bit shorter and it doesn't require the null checks.

**Comment by ice-blaze** [comment]
@crisbeto do you think it would be a good idea to update the Angular documentation with `hasError()`? This would improve consistency between the Angular documentation and the Material one."

**Comment by crisbeto** [comment]
I think it would be okay to send a PR to the main repo to update the docs there.

**Comment by crisbeto** [comment]
Closing this based on the discussion.

**Pull request closed without merging**
