### PR TITLE
Map overlay

### PR DESCRIPTION
**Pull request by mbehrlich**

### CODE REVIEW

**Comment by francovp** [comment]
Hello, In which version can I get this?

**Comment by jelbourn** [comment]
This feature will end up landing in `10.0.0` (and all of the `-next` and `-rc` pre-releases)

**Comment by francovp** [comment]
Oh,
Any idea how can I add this feature on a production ready Angular 9 project?

**Comment by jelbourn** [comment]
There's https://github.com/angular/google-maps-builds, but the builds there have zero guarantee of stability.

**Pull request merged**
