### PR TITLE
feat(drawer): add rail drawer support

### LINKED ISSUE #1728: Navigation drawer - Mini variant behavior
#### Feature request:
Add the "Mini variant" behavior of the Navigation drawer.
As defined in the Google Material guidelines:
https://material.google.com/patterns/navigation-drawer.html#navigation-drawer-behavior

#### What is the expected behavior?
When toggled, the navigation drawer change its width.
It's not fully hidden.

#### What is the current behavior?
Only two states are available: displayed, hidden

#### What are the steps to reproduce?
Create a sidenav and toggle it on and off.
The sidenav can only be opened or closed.
No intermediate state.

#### What is the use-case or motivation for changing an existing behavior?
Desktop users need to quickly change the current view.
The sliding effect of the sidenav could be annoying when used a lot.
It's common for desktop apps to keep the navigation opened by default.
But in some cases the icons are self explanatory so no need to display the associated labels.

#### Which versions of Angular, Material, OS, browsers are affected?
Angular2

#### Is there anything else we should know?
A similar feature request was submitted for Angular 1:
https://github.com/angular/material/issues/3158

### PR DESCRIPTION
**Pull request by Jordan-Hall**
Add rail support for the drawer.

Added a new mode for drawer rail `mode="rail"` inline with https://material.io/components/navigation-rail

This PR will resolve #1728 https://github.com/angular/components/issues/1728

### CODE REVIEW

**Comment by Jordan-Hall** [comment]
@googlebot I signed it!

**Comment by mmalerba** [comment]
This needs further design discussion between the Angular Components and MDC teams before we can proceed.  The spec seems to consider the navigation drawer and navigation rail to be different components. It may make sense to combine them, but I don't think this is something we can say for sure without further discussion.

**Comment by Jordan-Hall** [comment]
@mmalerba  the specs state its different, however then it goes onto say it can be used as a drawer. Angular Material  still need a different component  for rail itself. But it doesn't make sense to add the drawer functionality into rail itself

**Comment by TheNightmareX** [comment]
Useful features are always deposited

**Comment by Jordan-Hall** [comment]
@googlebot I fixed it

**Comment by devversion** [comment]
Hey, please re-open the pull request if still valid. The PR got auto-closed by GitHub when we renamed our primary branch.

**Comment by Jordan-Hall** [comment]
> Hey, please re-open the pull request if still valid. The PR got auto-closed by GitHub when we renamed our primary branch.

Depends if you want it. Still have it updated on a separate package. But last thing I heard, you was waiting on specs from material design.

**Comment by devversion** [comment]
I can't unfortunately give you a better response/update here since I haven't been involved in potential discussions here with the Material Design team. It's great to hear that you are maintaining this effort as a separate project though.

I would need to defer for updates/feedback on this to @mmalerba.

**Pull request closed without merging**
