### PR TITLE
build: update to latest MDC version

### PR DESCRIPTION
**Pull request by crisbeto**
Updates to the latest alpha version of MDC which includes some of the changes we need for the progress bar. Also fixes a breaking change in the tab styles.

### CODE REVIEW

**Comment by mmalerba** [comment]
I believe there were some breaking button changes that @andrewseguin mentioned, button might need some tweaks in this PR

**Comment by andrewseguin** [comment]
This causes buttons to lose their height since we now need to use their density system I think

mhKjHYBJrGY

I think it's fine to submit and I'll work on making the fixes

**Comment by crisbeto** [comment]
Pushed a fix for the button height.

**Comment by andrewseguin** [comment]
Great thanks

**Pull request merged**
