### PR TITLE
fix(material/datepicker): remove fixed width as not working on mobile

### PR DESCRIPTION
**Pull request by ajitsinghkaler**
In date picker the events example is not responsive on mobile because it has fixed width now changed it to max-width

Datepicker   Angular Material (1)

### CODE REVIEW

**Comment by mmalerba** [comment]
@ajitsinghkaler I would also be fine with just removing the `width`/`max-width` completely. I don't think it's really necessary.

**Comment by mmalerba** [comment]
The API golden checks is just something that was broken at head for a little while, this PR is fine

**Comment by ajitsinghkaler** [comment]
@mmalerba I've made the change can you please look into the request now.

**Comment by ajitsinghkaler** [comment]
@mmalerba now what do I have to do to get the checks right.

**Pull request merged**
