### PR TITLE
docs: improved contributing and coding standard docs

### PR DESCRIPTION
**Pull request by alkavats1**

### CODE REVIEW

**Review by crisbeto — COMMENTED** [review]
Can you clarify the changes here? They seem to be identical to what we currently have.

**Comment by alkavats1** [comment]
> Can you clarify the changes here? They seem to be identical to what we currently have.

Hi, @crisbeto Thanks for the comment. Yes sure, In the codinding_standard.md, I have updated the sentences according to the language tool. In summary, it is better to use "to" instead of over and instead of "all of the" to "all the".
And in the contributing.md, I have updated the "For individual we have.." to "For individual, we have .."
It is a better way to write a sentence.
Please verify and review
Thanks :)

**Comment by crisbeto** [comment]
Can you share a link?

**Review by andrewseguin — APPROVED** [review]

**Comment by andrewseguin** [comment]
These changes are a little arbitrary and in some cases subjectively better. Thank you for the contribution - we would encourage more substantial changes next time

**Comment by alkavats1** [comment]
Hi @alan-agius4 @josephperrott Could you please merge this PR?
Thanks

**Pull request merged**
