### PR TITLE
refactor: switch output event event classes to interfaces

### PR DESCRIPTION
**Pull request by crisbeto**
Converts the various event classes that we emit through `@Output` into interfaces in order to generate less compiled code and potentially less objects to garbage collect.

### CODE REVIEW

**Comment by crisbeto** [comment]
Caretaker note: we should keep an eye out on how many presubmit failures this causes and determine based on that whether it's still worth the trouble.

**Comment by rafaelss95** [comment]
FYI this fixes part of #7191.

**Comment by jelbourn** [comment]
@crisbeto I ran a presubmit on this and found that there are quite a few places where people `new` their own events in unit tests. Based on that, this would have to be a major change

**Comment by rafaelss95** [comment]
Any chance to ship this in v6?

**Comment by jelbourn** [comment]
This isn't going to make it in for 6.0 since it caused too many breakages inside Google. We should bump it to 7.0

**Comment by crisbeto** [comment]
Closing since this is way out of date.

**Pull request closed without merging**
