### PR TITLE
fix(material/core): Use aria-checked for checkbox option

### PR DESCRIPTION
**Pull request by clamli**
The `aria-selected` attribute is applied to pseudo checkboxes within mat-select multiple selection, which creates a visual and semantic discrepancy, as well as causing problems for screen readers that does not announce aria-selected status. This has resulted in a number of accessibility bugs being reported in the past.

It makes more sense to use `role='option'` for single selection mode and `role='checkbox'` for multiple selection mode. For checkboxes, we can use `aria-checked` to mark selection status, and for options, we can use `aria-selected`. Doing this would ensure that all screen readers announce the selection status consistently for multiple selection.

Demo recorded on Chrome + VO with the change, SR announces "selected/not selected" for single selection, and "checked/not checked" for multiple selection.

[Mat-select demo.webm](https://user-images.githubusercontent.com/20229878/228040205-911e5616-8805-4b46-8b57-fcb2ab629320.webm)

---
Demo recorded on Chrome + NVDA with the change, SR only announces "not selected" for single selection, and "checked/not checked" for multiple selection.

[AM-select NVDA.webm](https://user-images.githubusercontent.com/20229878/228340098-ed2a81b1-8cb0-40db-8afa-03f46a6a671c.webm)

---
Demo recorded on Chrome + JAWS with the change, SR does not announce selection status for single selection, and "checked/not checked" for multiple selection.

[AM-select JAWS.webm](https://user-images.githubusercontent.com/20229878/228340511-54ddf67e-d07a-4746-a252-6fe9ee8657c2.webm)

---
Demo recorded on Firefox + NVDA with the change, SR only announces "not selected" for single selection, and "checked/not checked" for multiple selection.

[AM-select NVDA firefox.webm](https://user-images.githubusercontent.com/20229878/228371609-57b584ff-8a5b-45e8-bd6e-03c7bf947a65.webm)

---
Demo recorded on Firefox + JAWS with the change,  SR does not announce selection status for single selection, and "checked/not checked" for multiple selection.

[AM-select JAWS firefox.webm](https://user-images.githubusercontent.com/20229878/228371709-efdf342e-4e22-439a-934e-95c3c2b13ce3.webm)

### CODE REVIEW

**Comment by jelbourn** [comment]
Some clarifications:

> The aria-selected attribute is applied to checkboxes within mat-select

I don't think this is quite accurate- the component applies `aria-selected` correctly to `role="option"`. It uses a visual indicator of selection that looks similar to a checkbox. If this visual indicator is the source of the bugs you're seeing, I would be more inclined to change the indicator than the actual interaction pattern / state model. 

> Mat-select is implemented as a `listbox`

Also not fully accurate- `MatSelect` is implemented as a _combobox_. From ARIA 1.2:

>Authors MUST ensure the popup element associated with a combobox has a role of [listbox](https://www.w3.org/TR/wai-aria-1.2/#listbox), [tree](https://www.w3.org/TR/wai-aria-1.2/#tree), [grid](https://www.w3.org/TR/wai-aria-1.2/#grid), or [dialog](https://www.w3.org/TR/wai-aria-1.2/#dialog).

So for select, IMO only `listbox` and `dialog` make sense here, and I strongly suspect combobox + listbox is the most frequently encountered and best supported option.

**Comment by clamli** [comment]
Thanks! Update the description to be more accurate.

**Review by zarend — COMMENTED** [review]
Hello, is there an issue report to reference for this PR?

**Comment by clamli** [comment]
This PR is based on an offline discussion, and there was a [previous attempt](https://github.com/angular/components/pull/26843#pullrequestreview-1359804607) to fix the issue.

**Comment by jelbourn** [comment]
@clamli we would also need to test
* Safari + VoiceOver
* Firefox + NVDA
* Firefox + JAWS
* TalkBack

**Comment by clamli** [comment]
I tested with VO + Safari, but I was unable to move the focus to the option inside mat-select to make it announced, record is attached below. This appears to be a known issue: https://github.com/angular/components/issues/24390, and the workaround is to [*navigate to the options*](https://github.com/angular/components/issues/24390#issuecomment-1400720512), however, I was not sure how I could navigate to option.

[AM-select issue.webm](https://user-images.githubusercontent.com/20229878/228394686-79427e8e-f164-42bd-bc2e-14dcdaf7aeba.webm)

It works well if I test the same combination on a native select.

[Native-select demo.webm](https://user-images.githubusercontent.com/20229878/228395276-0f8f2130-f157-4ab3-8e7b-4b8096b2fbe0.webm)

**Review by zarend — CHANGES_REQUESTED** [review]
Hello folks,

Some screen readers announce both selected and not selected options as "selected" or "not selected". Some will only announce which ones are not selected. There's no requirement that `<mat-option/>` needs to sound the same on every screenreader, and I believe it is correctly implementing ARIA and WCAG requirements.

There's room for bike shedding on aria-selected vs aria-checked, but I'm looking for a bug that it fixes or something to back up this proposal.

Also, the solution as written would need to update the accessibility documentation
 - select.md
 - autocomplete.md
 
 -Zach

**Comment by zarend** [comment]
Hello @clamli ,

Thank you for taking initiative on this. @jelbourn and I talked about this today. We believe that using aria-checked *may* be the right thing to do. Jeremy is going to reach out and get more information about this. We'll leave this PR open in the meantime.

-Zach

**Comment by clamli** [comment]
Hi Zach,

Thanks for following up! 
I'm putting this on hold for now, as both of the options I proposed have problem. I'm happy to share my findings so far and would love to hear your thoughts!

#### Option 1
```
@Component({
  selector: 'mat-option',
  host: {
    '[attr.role]': 'option',
    '[attr.aria-selected]': '_getAriaSelected()',
    '[attr.aria-checked]': '_getAriaChecked()'
  },
})

_getAriaSelected(): boolean | null {
    return this.multiple ? null : this.selected;
  }

_getAriaChecked(): boolean | null {
   return this.multiple ? this.selected : null;
}
```
This attempt uses aria-checked property for multiple selection mat-option, but VoiceOver seems to have difficulty recognizing aria-checked status inside an option, instead, it keeps looking for aria-selected, since that is not provided, it reads out "not selected" for all options regardless of their selection status.

#### Option 2
```
@Component({
  selector: 'mat-option',
  host: {
    '[attr.role]': '_getRole()',
    '[attr.aria-selected]': '_getAriaSelected()',
    '[attr.aria-checked]': '_getAriaChecked()'
  },
})

_getRole(): string {
    return this.multiple ? 'checkbox' : 'option';
  }

_getAriaSelected(): boolean | null {
    return this.multiple ? null : this.selected;
  }

_getAriaChecked(): boolean | null {
   return this.multiple ? this.selected : null;
}
```
This attempt uses role='checkbox' with aria-checked property, and role='option' with aria-selected. The screen reader results look good as posted in the description.
However, according to [WAI-ARIA listbox](https://www.w3.org/TR/wai-aria/#listbox), "option" is a required owned element of any element with role="listbox". Since mat-select is a combobox implemented as a listbox, we have to set role="option" for the option inside.

**Comment by crisbeto** [comment]
Closing since this is way out of date and it looks like the discussion didn't end up anywhere.

**Pull request closed without merging**
