### PR TITLE
Switch the CDK to input transforms

### PR DESCRIPTION
**Pull request by crisbeto**
Reworks most of the places where we use input coercion in the CDK to input transforms.

### CODE REVIEW

**Review by devversion — APPROVED** [review]
LGTM but I think we should reach consensus on https://angular-team.slack.com/archives/C040TF8UT/p1694087146008889 sooner than later- because we are clearly opening up the types to _anything_ with a PR like this

**Comment by andrewseguin** [comment]
+1 @devversion Would be good to get this clarified before the release

Also - we should mark the current coercion functions as deprecated so that we can remove them in v19

**Review by josephperrott — APPROVED** [review]
LGTM

**Comment by crisbeto** [comment]
We discussed this today during standup. I'll merge this PR and work on making the typings stronger on the FW side before v17.

**Pull request merged**
