### PR TITLE
docs(material/theming): get-color-from-palette passes in '500' instead o…

### LINKED ISSUE #27630: docs-bug(theming): get-color-from-palette passes in '500' instead of 500
### Documentation Feedback

In the Reading hues from palettes section in the first code snippet. 
It sets the background using `mat.get-color-from-palette($my-palette, '500')` which will not apply the styles and it should be `mat.get-color-from-palette($my-palette, 500)`

### Affected documentation page

https://material.angular.io/guide/theming#reading-hues-from-palettes

### PR DESCRIPTION
**Pull request by nathanejbrown**
…f 500

Changes value in doc from string to number

fixes #27630

### CODE REVIEW

**Comment by nathanejbrown** [comment]
I'm not sure why there's a CLA issue -- I've quadruple checked the information that I filled the CLA out with and it all looks correct

**Comment by json-derulo** [comment]
Duplicate of #27639

**Comment by nathanejbrown** [comment]
I knew I was gonna miss something. Commit message should be fine now

**Review by mmalerba — APPROVED** [review]
LGTM

**Pull request merged**
