### PR TITLE
feat(material/select): harness throw when options are requested but panel is closed

### LINKED ISSUE #26986: feat(mat-select): Improve mat-select harness DX
### Feature Description

Currently, when using `matSelectHarness.getOptions()`, an empty array is returned if the `matSelectHarness.open()` method is not called beforehand. This can be confusing for users, who may not realize they need to call `matSelectHarness.open()` first.

To improve the user experience, I suggest adding an error message similar to what is done in `matAutoCompleteHarness`, so that if `getOptions()` is called before `open()`, an error will be thrown informing the user to call `open()` first.

This change would save users time and frustration by providing immediate feedback on what they need to do to correctly use the `getOptions()` method.

matAutoComplete implementation:
https://github.com/angular/components/blob/22e928c4fce56fc3619e7aecd0affbb8972847ae/src/material/autocomplete/testing/autocomplete-harness.ts#L80

I can make a PR for it :)

Thanks.

### PR DESCRIPTION
**Pull request by behzadmehrabi**
Closes #26986.

### CODE REVIEW

**Comment by crisbeto** [comment]
Sorry the delay in reviewing this. Can you rebase the PR?

**Review by crisbeto — APPROVED** [review]

**Comment by crisbeto** [comment]
I ran the changes against all of our internal apps and it turned out to be quite breakey. It looks like a lot of apps are calling `getOptions` on a closed select.

**Comment by behzadmehrabi** [comment]
haha :)) thanks for notifying.

**Comment by crisbeto** [comment]
Closing given how breaking the change would be.

**Pull request closed without merging**
