### PR TITLE
feat(cdk/drag-drop): support configurable propagation of mousedown an…

### PR DESCRIPTION
**Pull request by lincolnthree**
Fixes: https://github.com/angular/components/issues/19333

### CODE REVIEW

**Comment by lincolnthree** [comment]
@googlebot I signed it!

**Comment by lincolnthree** [comment]
Fixed build error.

**Comment by lincolnthree** [comment]
Hey, @crisbeto Thanks for reviewing. 

In this case, we don't have control over the event listener bindings (and to be most configurable, I'd think the option would help people integrate with additional frameworks more easily.) To which other events are you referring?

Would it make sense if the property were named something more specific, like, "propagateNativeDomEvents"?

**Comment by pycraft114** [comment]
@crisbeto Hi :) 
What is the recommended way you suggest to propagate an event?

**Comment by crisbeto** [comment]
Sorry for the delayed response, I must've missed the notification. I'm still not sold on the idea of this being a public API since it assumes that people would know the internals of the `drag-drop` module. WDYT @jelbourn?

**Comment by lincolnthree** [comment]
My 2 cents, summarized, and sorry if this sounds at all like a lecture or telling you what to do, I'm already working on a fork and this not being included will not really affect me -- just trying to be helpful and give a "real world" perspective that I think will help people: 

Drag & Drop is part of the angular "component development kit", and people need control over how it behaves when building custom components. Without fine-grained control, ability to use features will be extremely limited to niche use-cases that you guys think up but that may not exactly fit real-world scenarios. 

PS. I have other config features along these lines that I would submit if you folks are interested. Ability to disable the placeholder element, for instance. Support for centering the preview elements on the fired event coordinates. Etc.

This is the kind of fine-control needed to really build custom components for highly customized apps, which I assume is your goal :) Without it I'll just continue to fork. But it's here if you want it.

**Comment by jelbourn** [comment]
Looking at the code, it seems like calling `stopPropagation` isn't a feature or an intended observable behavior, but is instead just an implementation details to prevent nested dragging interactions from breaking. As such, adding a config option to control this implementation detail seems problematic. 

My take it that it would be better to solve the nested dragging issue another way, such that the component doesn't have to call `stopPropagation` at all. Then the events work as expected and no public API is necessary.

**Comment by lincolnthree** [comment]
Fine by me. I don't actually believe this call to `stopPropagation()` is necessary in the first place, but I don't know the internal details  ;) and I figured a configuration option was safer.

**Comment by lschuft** [comment]
Hello! What's the status on this? Is it waiting for corrections, or it will not be merged altogether? I currently have a [use case](https://stackblitz.com/edit/components-issue-wdnqmc) that manifests this issue where this public API would be useful.

I agree that this would assume people know the internals of the drag-drop module, but stopping event propagation [is actually quite dangerous](https://css-tricks.com/dangers-stopping-event-propagation/) because it breaks the event listening flow of apps and even third-party libraries. And worse, we can't actually fix it without removing whatever code is calling stopPropagation(). 

While dangerous, the stopPropagation() in this case is useful to avoid breaking nested scenarios. But if the drag-drop consumer does not use nesting, then he should be able to deactivate its usage. So this option would be useful if a refactoring is not planned for the near-future.

**Comment by crisbeto** [comment]
The underlying issue should've been resolved in https://github.com/angular/components/pull/21227 so I'll close this PR.

**Comment by lincolnthree** [comment]
Very good. Thanks for finding a solution. Getting closer to a usable basis for custom D&D needs.

**Pull request closed without merging**
