### PR TITLE
feat(material/snack-bar): Switch snack-bar implementation to use MDC

### PR DESCRIPTION
**Pull request by mmalerba**
Old implementation is still available under @angular/material/legacy-snack-bar

BREAKING CHANGE:
- DOM and CSS classes for mat-snack-bar have changes
- Typescript API is largely the same but may have minor differences
- See the MDC migration guide for more information about the changes and
  how to migrate your app (TODO: link when available)

### CODE REVIEW

**Comment by mmalerba** [comment]
@crisbeto do you know whats up with this test failure: "theming api should warn if default density styles are duplicated"

It looks like the mdc-button density styles are missing. I *did* touch those styles a bit because I found that button density was under "unmigrated-component-densities" and icon-button, fab were just missing. I'm not sure why the test is failing though. If anything my change should have fixed it since it added the missing mixins

**Comment by crisbeto** [comment]
I would have to dig into why that test is failing, but from what I can tell, it is related to MDC's styles, because excluding this mixin fixes the test failure https://github.com/angular/components/blob/main/src/material/button/_icon-button-theme.scss#L55. Maybe it's being generated under the wrong selector?

**Comment by andrewseguin** [comment]
Yeah I remember getting that when I had the wrong names in `private-check-duplicate-theme-styles`

**Comment by mmalerba** [comment]
Based on my understanding of the test, it looks like `@include angular-material-density(0);` is somehow producing a different result for mat-icon-button than `@include angular-material-theme(mat-light-theme((color: (...))));`. This is odd because it produces the same result for every other component

**Comment by mmalerba** [comment]
Mystery solved: the function we had to compare CSS output didn't know how to handle comments, which was causing it to say that the outputs weren't equivalent

**Review by andrewseguin — APPROVED** [review]

**Review by wagnermaciel — APPROVED** [review]
lgtm

**Pull request merged**
