### PR TITLE
feat(sort-header): allow a readable label to be provided to be used in the sort-header aria-label

### LINKED ISSUE #11136: Screen-reader announces wrong name for first table cell
### Summary
Upon Screen Reader focus set on column 1, row 1 i.e. 'dessert (100g) ' , observe Screen Reader does not announce the name correctly. 

### Reproduction on material.angular.io
1. Linear navigate to ' Components ' menu item and click 'Enter' to open components page.                                                                                                                                                                                                                                          
2. Linear navigate forward and set focus on expand collapse left hand menu item ' Navigation'                                                                                                                                                                                                                                  
3. Click 'Enter' key to expand OR collapse this menu item                                                                                                                                                                                                                                                                                       
4. Linear navigate into 'sort header' & click ENTER keystroke.                                                                                                                                                                                                                                                                                   
5. Navigate into tabs "Examples" and Click ENTER                                                                                                                                                                                                                                                                                 
6. Navigate and set focus on column 1, row 1 i.e. 'dessert (100g) '

### PR DESCRIPTION
**Pull request by josephperrott**
Fixes #11136

### CODE REVIEW

**Comment by crisbeto** [comment]
I've got https://github.com/angular/material2/pull/13297 that somewhat goes against this one, because it'll remove the `aria-label` altogether. The problem with having an `aria-label` is that it'll be read out for every cell that the user navigates to, instead of only when they're on the header.

**Comment by josephperrott** [comment]
@andrewseguin Can you take a look at these options and determine how you think its best to proceed for sort header?

**Comment by josephperrott** [comment]
@andrewseguin Updated to include changes we discussed about the `aria-label` in the header.

@crisbeto Can you take another look?  I think its important that the button still has an `aria-label` defining its action, and this method will allow this and make the `aria-label` that is read for the cell make sense in the context of the table.

**Comment by jelbourn** [comment]
@josephperrott I believe setting `aria-sort` instead of `aria-label` is the right thing

**Pull request closed without merging**
