### PR TITLE
fix(material-experimental/mdc-checkbox): fix broken dark theme

### PR DESCRIPTION
**Pull request by mmalerba**
This is a re-submit of https://github.com/angular/components/pull/20926 with a fix for the focus state

### CODE REVIEW

**Review by wagnermaciel — APPROVED** [review]
lgtm

**Comment by crisbeto** [comment]
What is broken in the current dark theme styles? It seemed to work for me in the dev app.

**Comment by wagnermaciel** [comment]
> What is broken in the current dark theme styles? It seemed to work for me in the dev app.

We had a screenshot failure from the previous change where the focus state of a checkbox was not the correct color (I think it was darker than it was supposed to be). I'm not super familiar with mdc-checkbox so I don't fully understand why, but the changes in this PR have fixed the issue. I'm working on getting it submitted as quickly as possible

**Comment by mmalerba** [comment]
I forgot to include the styles to re-color the ripple for primary, accent, warn states - so the ripple was always gray. Fixed it in this PR

**Comment by crisbeto** [comment]
@wagnermaciel I meant to ask what issue was the original PR fixing, before we had to revert it.

**Comment by wagnermaciel** [comment]
@crisbeto I'm not sure. @mmalerba might have the answer you're looking for

**Pull request merged**
