### PR TITLE
refactor: change templateUrl and styleUrls to use absolute paths

### PR DESCRIPTION
**Pull request by rafaelss95**
**Current behavior**:

Captura de Tela 2020-08-12 às 19 22 04
Captura de Tela 2020-08-12 às 19 22 31

With this change, the tab labels become CSS and HTML as usual, instead of the file paths and also the stackblitz folder structure will be correct.

### CODE REVIEW

**Comment by devversion** [comment]
Yeah, agreed. The paths should be normalized in the docs site, or at minimum in the example module generation (see `tools/example-module` folder).

**Comment by rafaelss95** [comment]
I agree with you, but almost all of the paths in the repo are not relative, these here are outside the rule. I think the best thing to do now is to fix the broken examples and then try to change the document generation or anything else.

Anyway, let me know the path you would want proceed with this PR.

**Comment by devversion** [comment]
I think it's totally fine using either `./my-file.css` or `my-file.css`. Both are relative paths starting with the directory that contains the declaring component file. Updating the docs to deal with non-normalized paths shouldn't be any slower than making the examples use non-enforced path conventions.

**Comment by devversion** [comment]
I'd personally prefer closing this PR and just fixing this in the docs site. Happy to accept a PR if you'd like to take a look there. Thanks anyway for trying to fix this (even with this PR).

**Comment by jelbourn** [comment]
+1 to @devversion, the urls here are valid, even if our other tooling has issues; I'd rather focus on fixing the tooling

**Comment by rafaelss95** [comment]
No problem guys. When I have some time left, I take a look at document generation.

**Pull request closed without merging**
