### PR TITLE
refactor(cdk/overlay): remove deprecated connected position strategy

### PR DESCRIPTION
**Pull request by crisbeto**
The `ConnectedPositionStrategy` has been deprecated since at least 7.0.0 and is just a wrapper around `FlexibleConnectedPositionStrategy`. These changes remove it since it still adds a fair bit of code that has to be maintained.

BREAKING CHANGE:
* `ConnectedPositionStrategy` has been removed. Use `FlexibleConnectedPositionStrategy` instead.
* `OverlayPositionBuilder.connectedTo` has been removed. Use `OverlayPositionBuilder.flexibleConnectedTo` instead.

### CODE REVIEW

**Comment by crisbeto** [comment]
Caretaker note: let's decide how to proceed with this one based on the number of usages we see in g3.

**Comment by Splaktar** [comment]
Was there already a migration for this applied in a previous release?

**Comment by crisbeto** [comment]
There's no easy way to migrate this for people. The position strategy has been deprecated since March 2018 so there's been a lot of time to migrate away from it.

**Comment by andrewseguin** [comment]
This passes global presubmit - will be merged in the next round

**Review by Splaktar — APPROVED** [review]
LGTM

**Pull request merged**
