### PR TITLE
feat(table): add data on cdk row

### LINKED ISSUE #14807: [CdkTable] Set data on row like in the CdkTreeNode
#### Please describe the feature you would like to request.
I'd like to have the data set on the CdkRow similar to the CdkTreeNode in the CdkTree.

#### What is the use-case or motivation for this proposal?
This would make it possible to use a TreeControl and a FlatTreeDataSource with the table and have the TreeControl work with the CdkRow as well. A table with a tree like behaviour would be possible with the Cdk components.

```
export class CdkTable {
...
  private _insertRow(renderRow: RenderRow<T>, renderIndex: number) {
    const rowDef = renderRow.rowDef;
    const context: RowContext<T> = {$implicit: renderRow.data};
    this._renderRow(this._rowOutlet, rowDef, renderIndex, context);

    // Set the data to just created `CdkRow`.
    // The `CdkRow` created from `createEmbeddedView` will be saved in static variable
    //     `mostRecentRow`. We get it from static variable and pass the row data to it.
    if (CdkRow.mostRecentRow) {
      CdkRow.mostRecentRow.data = renderRow.data;
    }
  }
...
}
```

```
export class CdkRow<T> implements OnDestroy {

  /**
   * The most recently created `CdkRow`. We save it in static variable so we can retrieve it
   * in `CdkTable` and set the data to it.
   */
  static mostRecentRow: CdkRow<any> | null = null;

  data: T;

  constructor() {
    CdkRow.mostRecentRow = this as CdkRow<T>;
  }

  ngOnDestroy() {
  // If this is the last row being destroyed,
  // clear out the reference to avoid leaking memory.
  if (CdkRow.mostRecentRow === this) {
    CdkRow.mostRecentRow = null;
    }
  }
}
```
#### Is there anything else we should know?

This change would make the CdkRow a generic class CdkRow<T> since the data property is of type T. Same as the CdkTreeNode

### PR DESCRIPTION
**Pull request by ffriedl89**
closes #14807 
I guess this change would introduce a breaking change of the public api since it changes the CdkRow to a generic class

### CODE REVIEW

**Comment by ffriedl89** [comment]
I signed it!

**Comment by ffriedl89** [comment]
Thanks for you quick response, i've added an example that uses the cdk classes and extends them to create a tree-table like demo. I had to work around some issues in the generate-examples-module tooling. I had to separate the declarations from the entry components since i used directives in my demo. I am looking forward to your feedback about my approach :)

**Comment by andrewseguin** [comment]
Hey @ffriedl89, thanks for providing the example of what you are looking for with these changes.

It seems to me that you can add this tree functionality without any code changes to the table by just using the `MatTreeFlatDataSource`. This may be better since it reduces our coupling between the tree and table.

Check out this example and let me know what you think:
https://stackblitz.com/edit/angular-m77g7e?file=app%2Ftable-basic-example.ts

**Comment by ffriedl89** [comment]
Hi @andrewseguin,
thanks a lot for the example. I was able to improve my code by removing the connection to the cdktree.
To give a little bit of context - i am currently using the cdk to create an angular component library and i want to provide a reusable tree-table component. The issue that remains is - when using the cdk table to create a reusable tree-table component that handles indentation and the toggle internally - like in a toggle-cell - you would not have the data available on the row. But you would need the data for the treecontrol toggling/expansionmodel. 
When doing this inside the template like in your example you have access to the row data because it's set as the context on the cdkCellDef. Inside the instance for each row you cannot access the implicit context and therefore you cannot use the treeControl because you lack the data.

**Comment by jelbourn** [comment]
Closing this since I'm not super clear on what the goal was. WRT `TreeControl`, I would like to move away from the `TreeControl` concept in the future for cdk tree, but that will need some more thought.

**Pull request closed without merging**
