### PR TITLE
fix(material/chips): fix ripple element opacity when using CSS variable theming

### LINKED ISSUE #17577: Chips: Opacity is not added to the ripple element when using CSS variables to define a custom theme
In the bug demo below, I use CSS variables to define a custom theme (so I can change it dynamically). Please see the '_styles.scss_' file.

**Demo:** https://stackblitz.com/github/JoakimZebic/angular-material-chips-bug-report

**Steps to reproduce:**
1. Click on any 'colored' chips

**Expected Behavior**
Ripple effect should have opacity.

**Actual Behavior**
Ripple is a solid color (depending on the contrast color of the theme) and doesn't have opacity.

**Environment**

- Angular: 7.2.0
- CDK/Material: 7.3.7
- Browser(s): Chrome, Firefox
- Operating System (e.g. Windows, macOS, Ubuntu): Windows 10

### PR DESCRIPTION
**Pull request by JoakimZebic**
Fixes a bug in the Angular Material `chips` component where ripple element doesn't have opacity when CSS variables are used to make a dynamic theme

Fixes #17577

### CODE REVIEW

**Comment by JoakimZebic** [comment]
> The changes look good, but some of the CI checks are failing.

Thanks for the review. I will take a look again at these tests, but I had some issues with executing them.

**Comment by crisbeto** [comment]
The test failures look like flakes so you should be able to resolve them by rebasing. The lint failure looks real though.

**Comment by JoakimZebic** [comment]
Thank you. 
Lint failure is some trailing whitespace (most likely). I will look into it. :)

**Comment by JoakimZebic** [comment]
@googlebot I fixed it.

**Comment by crisbeto** [comment]
The CLA error is because you pushed the commits from two separate email addresses.

**Comment by mmalerba** [comment]
It looks like similar changes got merged in #17649, we can either rebase this one and merge it to extract the separate mixin, or just close it.

@jelbourn @crisbeto

**Comment by jelbourn** [comment]
@JoakimZebic this passes Google's internal presubmit, just needs a rebase

**Comment by mmalerba** [comment]
@jelbourn I took care of it

**Pull request merged**
