### PR TITLE
fix(material-experimental/mdc-list): fix typo in action-list css class

### PR DESCRIPTION
**Pull request by mmalerba**

### CODE REVIEW

**Review by andrewseguin — APPROVED** [review]

**Review by wagnermaciel — APPROVED** [review]
LGTM

**Review by devversion — APPROVED** [review]
😱

**Comment by devversion** [comment]
Out of curiosity: Did this cause any visual differences/problems for the action list?

**Comment by mmalerba** [comment]
It caused a small difference, the action list was missing a bit of padding at the top/bottom. That's actually how I discovered this, noticed that action list looked a little different compared to the other variants

**Comment by devversion** [comment]
I see, thanks for the details @mmalerba!

**Pull request merged**
