### PR TITLE
docs(material-experimental): fix scss examples

### PR DESCRIPTION
**Pull request by macjohnny**
Fixes the error
```
Error: ./src/styles.scss
Module build failed (from ./node_modules/mini-css-extract-plugin/dist/loader.js):
ModuleBuildError: Module build failed (from ./node_modules/sass-loader/dist/cjs.js):
SassError: Missing argument $config-or-theme.
   ┌──> src\styles.scss
14 │ @include mat-mdc-select-typography();
   │ ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ invocation
   ╵
   ┌──> node_modules\@angular\material-experimental\mdc-select\_select-theme.scss
82 │ @mixin mat-mdc-select-typography($config-or-theme) {
   │        ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ declaration
   ╵
  src\styles.scss 14:1  mat-mdc-select-typography()
```

Note: the same problem also occurs in 
```
src\material-experimental\mdc-autocomplete  (1 usage found)
            README.md  (1 usage found)
                73 @include mat-mdc-autocomplete-typography();
        src\material-experimental\mdc-checkbox  (1 usage found)
            README.md  (1 usage found)
                69 @include mat-mdc-checkbox-typography();
        src\material-experimental\mdc-menu  (1 usage found)
            README.md  (1 usage found)
                73 @include mat-mdc-menu-typography();
        src\material-experimental\mdc-paginator  (1 usage found)
            README.md  (1 usage found)
                69 @include mat-mdc-paginator-typography();
        src\material-experimental\mdc-progress-bar  (1 usage found)
            README.md  (1 usage found)
                70 @include mat-mdc-progress-bar-typography();
        src\material-experimental\mdc-progress-spinner  (1 usage found)
            README.md  (1 usage found)
                70 @include mat-mdc-progress-spinner-typography();
        src\material-experimental\mdc-select  (1 usage found)
            README.md  (1 usage found)
                77 @include mat-mdc-select-typography();
        src\material-experimental\mdc-slide-toggle  (1 usage found)
            README.md  (1 usage found)
                69 @include mat-mdc-slide-toggle-typography();
        src\material-experimental\mdc-tabs  (1 usage found)
            README.md  (1 usage found)
                73 @include mat-mdc-tabs-typography();
```

### CODE REVIEW

**Comment by macjohnny** [comment]
alternatively, the default parameter could be set to `null`, similar to
https://github.com/angular/components/blob/2f61895659776f3be2734de0df70966e0754d984/src/material-experimental/mdc-typography/_all-typography.scss#L3-L10

**Review by crisbeto — APPROVED** [review]
LGTM

**Comment by macjohnny** [comment]
@crisbeto should I open a separate PR that fixes all other docs, too?

**Comment by crisbeto** [comment]
It's your call, docs PRs don't need to run through our presubmit process so it doesn't really matter if it's separate PRs or one large PR.

**Pull request merged**
