### PR TITLE
build: use platform from shared dev-infra package for remote execution

### PR DESCRIPTION
**Pull request by devversion**
Uses the new shared RBE platform from the dev-infra package.

We introduced a shared Bazel platform for remote execution builds
using Google cloud. Previously we used `bazel_toolchains` for
providing the platform w/ additional CPP and Java toolchains

`bazel_toolchains` no longer provides default toolchains with the
latest version, but provides a tool (linux and windows only) for
generating toolchain/platforms, which then need to be checked
into the repository. This is quite inconvenient and cumbersome
(especially with no macOS support), so we just provided our own
platform and CPP toolchain within `//dev-infra`. This is more
simple than all the effort we'd need to make the toolchain
generation tool work (while it would also increase the amount
of checked-in sources significantly; with more unused toolchains
for CPP or Java)

See: https://github.com/angular/angular/pull/41767.

### CODE REVIEW

**Review by crisbeto — APPROVED** [review]
LGTM

**Review by josephperrott — APPROVED** [review]
LGTM

**Comment by andrewseguin** [comment]
Needs rebase

**Comment by devversion** [comment]
@andrewseguin Done

**Pull request merged**
