### PR TITLE
fix(focus-trap): expose focus trap methods on directive #7979

### PR DESCRIPTION
**Pull request by amcdnl**
Hides the focus trap instance and exposes the functions on the directive. Addresses #7979

### CODE REVIEW

**Comment by jelbourn** [comment]
This is technically a breaking change. Can you make the internal `focusTrap` deprecated instead of private?

**Comment by amcdnl** [comment]
Done.

**Comment by jelbourn** [comment]
@amcdnl lint error
```
ERROR: /home/travis/build/angular/material2/src/cdk/a11y/focus-trap.spec.ts[4, 9]: 'FocusTrap' is declared but never used.
```

FYI I know some folks add lint as a pre-commit hook in git

**Comment by amcdnl** [comment]
@jelbourn - done :)

**Comment by jelbourn** [comment]
It looks like there are some failures on travis- are those related to this PR?

**Comment by amcdnl** [comment]
@jelbourn - Export was renamed in merge, corrected and pushed :).

**Comment by josephperrott** [comment]
@amcdnl Go ahead and rebase and we can work on getting this in.

**Comment by amcdnl** [comment]
@josephperrott - rebased

**Comment by jelbourn** [comment]
Closing this since we've decided it's not super high priority

**Pull request closed without merging**
