### PR TITLE
Revert "feat(icon): add test harness (#20072)"

### PR DESCRIPTION
**Pull request by wagnermaciel**
This reverts commit 092b1515f3843a043884ee09b459c55ec3166213.

This change adds an import to icon-harness-filters.ts which breaks
the internal target which uses this file because it does not have
cdk/testing in it's deps.

### CODE REVIEW

**Comment by crisbeto** [comment]
Which import is this referring to? All imports to `icon-harness-filters.ts` are inside the `icon/testing` entry point itself.

**Comment by devversion** [comment]
It sounds like the internal test target just would need to be updated to include `cdk/testing` in the deps for `icon/testing`.

**Comment by wagnermaciel** [comment]
Yep, so this change needs to be added like a regular PR so it can be submitted by itself and fixed as part of the same submission. It can't be grouped in with the merge safe PRs or this error will show up for each PR we try to merge after it until the fix is made

**Comment by wagnermaciel** [comment]
@andrewseguin Is there another way to do this where we wouldn't have to revert this PR?

**Comment by wagnermaciel** [comment]
Change of plans, I'll leave this as is and patch a fix for each of the presubmits :+1:

**Pull request closed without merging**
