### PR TITLE
Cherry pick 23262 for date-fns-adapter

### PR DESCRIPTION
**Pull request by zarend**
cherry picks pr#23262 to 12.2.x. That PR was supposed to go into the `12.2.0` release, but it was merged into only the `master` branch by clicking `Merge` on the github UI 🤦 . It would have gone into `12.2.0` if it was merged with the release tooling. This will merge it into the `12.2.x` branch so it goes out with the release of `12.2.1` this week.

### CODE REVIEW

**Review by crisbeto — APPROVED** [review]
LGTM

**Comment by mmalerba** [comment]
I think we decided to release this as part of 13.0.0, so closing this PR

**Comment by mmalerba** [comment]
sorry, misunderstanding on my part - re-opening this

**Comment by zarend** [comment]
Closing this PR since it has become stale.

**Pull request closed without merging**
