### PR TITLE
feat(cdk/drag-drop): support configurable propagation of mousedown and touchstart events.

### PR DESCRIPTION
**Pull request by pycraft114**
fix for: [#19334](https://github.com/angular/components/pull/19334)

### CODE REVIEW

**Comment by pycraft114** [comment]
@googlebot I signed it!

**Comment by pycraft114** [comment]
@lincolnthree Looks like I need your consent :)

**Comment by lincolnthree** [comment]
@googlebot I consent.

**Comment by lincolnthree** [comment]
@pycraft114 Thank you very much!

**Comment by bvkimball** [comment]
Is there a timeline on getting this merged?

**Comment by lschuft** [comment]
+1. I'm having an [issue](https://stackblitz.com/edit/components-issue-wdnqmc) where this fix would be useful!

**Comment by crisbeto** [comment]
It looks like this should've been resolved by #21227. Closing.

**Pull request closed without merging**
