### PR TITLE
fix(material/datepicker): adjust focused date background for better visibility

### PR DESCRIPTION
**Pull request by annieyw**
Fixes: https://github.com/angular/components/issues/18845

Before:
A6ZjRCNQQNuinkY

After:
8Pobz56tMEDUwft
8xAbQdUmWJyCZFv

### CODE REVIEW

**Comment by jelbourn** [comment]
What are the contrast ratios on the text with the new treatment?

**Comment by annieyw** [comment]
5 for dark mode and 11.73 for light mode

**Comment by annieyw** [comment]
This is what it looks like with the range, I think it still looks fine, what do you think?
6mZ7NzpcseP46vT
I chose to use a color background because https://material.io/components/date-pickers#anatomy (Desktop date picker
section)

**Comment by mmalerba** [comment]
Ah I scanned the spec but didn't notice that. In that case yeah, lets go with the color

**Comment by mmalerba** [comment]
For reference, here's what it looks like when overlapping the green and yellow:
image

It's not my favorite, but good enough

**Review by mmalerba — APPROVED** [review]
LGTM

**Comment by crisbeto** [comment]
Looking through the designs in the spec (https://material.io/components/date-pickers#desktop-pickers), it seems like the circle is supposed to be transparent with an outline when selecting a range. It may end up complicating the selectors though.

**Comment by annieyw** [comment]
For the part where it says not to use the same style for hover and selected states I think it refers to selected range vs to be selected range. However it does seem like the datepicker and date range picker have slightly different hover state treatments.

**Comment by annieyw** [comment]
Confirmed with MDC designer that hover over selected range should be same as normal datepicker
unnamed

**Review by jelbourn — APPROVED** [review]
LGTM

**Pull request merged**
