### PR TITLE
bugfix: modified table predicate filter

### PR DESCRIPTION
**Pull request by daniel-brenot**
Replaces the string concatenation and index search with the .some check and a contains check. This should not be less efficient since the data is only getting checked once per row instead of twice, and the row will stop being looped over if a match is found earlier. Also removes unlikely edge case of a user inputing an obscure unicode character.

### CODE REVIEW

**Review by andrewseguin — COMMENTED** [review]
Performance-wise, I'm concerned that it's more expensive to call `toLowerCase` and `includes` for each column instead of once for each row after concatenating the values together. I'm sure the difference is small for most tables, but the solution may not scale to tables with many columns

**Comment by daniel-brenot** [comment]
I will run a performance benchmark in an onlike benchmark comparison and post a link

**Comment by daniel-brenot** [comment]
After testing using JSBench i have found the original algorithm to be 68% slower on average in the tests I made. You can confirm with the following jsbench snippet: https://jsbench.me/4bkjp85g44/1

**Comment by daniel-brenot** [comment]
Bumping because of inactivity.

**Comment by andrewseguin** [comment]
@daniel-brenot Sorry for the inactivity - the change looks okay to me and we can run it by internal tests to confirm that it works well. Can you rebase?

**Comment by daniel-brenot** [comment]
I pulled the upstream into the the branch and it should be good now. Let me know if theres anything else i need to do.

**Comment by andrewseguin** [comment]
I'm still seeing a note that "This branch cannot be rebased due to conflicts". You may want to perform a rebase with the original commit

**Comment by andrewseguin** [comment]
Will try to land this in https://github.com/angular/components/pull/30172

**Pull request closed without merging**
