### PR TITLE
build: update to rules_nodejs 1.0.0

### PR DESCRIPTION
**Pull request by gregmagolan**
Dependency sandwich exists between material & angular so we need to patch both @angular/bazel & ts-api-guardian npm packages to land this so that the material-unit-test CI job in https://github.com/angular/angular/pull/34589 can be greened up.

### CODE REVIEW

**Comment by gregmagolan** [comment]
@devversion I introduced the patch-package tool which is a nicer workflow for patching npm packages. A lot of the code from post install patches .js could be put into `/patches/` patch files instead which would be a better workflow IMO. I'll leave that up to you and I can switch to post install patches .js in this PR if that is preferred.

**Comment by gregmagolan** [comment]
Oh nice. I didn't notice you had a convenient patchPackage() function in your postinstall .js. Switched the patches over to there. Thanks!

**Comment by gregmagolan** [comment]
Ready to merge

**Comment by devversion** [comment]
Thanks for addressing the feedback. We want the changes between the patch branch and master branch to be as minimal as possible, so I think we want `target: patch`. Also `master` is the patch branch at the moment until v9 stable has been released.

**Comment by gregmagolan** [comment]
👍 SGTM

**Pull request merged**
